### PR TITLE
workflows: Add build and deploy on release tag workflow

### PR DESCRIPTION
**Pull request by alexgg**
This workflow will launch a Jenkins build and draft deploy job when a new
tag is made.

Changelog-entry: Add build and deploy workflow
Signed-off-by: Alex Gonzalez <alexg@balena.io>

### CODE REVIEW

**Comment by floion** [comment]
@balena-ci retest

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
```
leviathan-v2-template-client-1  | [2022-06-27T10:01:28.194Z][59415ad-os] Unable to exec
leviathan-v2-template-client-1  | [2022-06-27T10:01:28.194Z][59415ad-os] Error while performing SSH command "md5sum --quiet -c /resinos.fingerprint", will retry...
```

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@balena-ci retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@balena-ci rebase

**Pull request merged**
