### PR TITLE
linux-raspberrypi: Add IIO pressure kernel drivers

### LINKED ISSUE #821: Request to include iio/pressure bmp280 driver
Support request to use this driver with applications. It is included by default in the RPI4 defconfig but not other.

 See https://jel.ly.fish/support-thread-discourse-355354

### PR DESCRIPTION
**Pull request by alexgg**
These have been requested by customers to use with their applications.

Fixes #821

Changelog-entry: Add IIO pressure kernel drivers
Signed-off-by: Alex Gonzalez <alexg@balena.io>

### CODE REVIEW

**Comment by floion** [comment]
@alexgg is this still draft?

**Comment by alexgg** [comment]
@floion just need to check that the module is actually being included on the built images

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
lgtm

**Pull request merged**
