### PR TITLE
Draft: Fix/revpi connect 4 rs485

### PR DESCRIPTION
**Pull request by wickywaka**
There is something missing in the device trees because of which the RS-485 does not work. In this PR we will try to address that.

### CODE REVIEW

**Comment by floion** [comment]
Hi @wickywaka are you still working on this PR?

**Comment by wickywaka** [comment]
> Hi @wickywaka are you still working on this PR?

Hi @floion we stopped working on this and are waiting for the Kunbus to add official support for this device. Here is the thread where we discussed this:
https://revolutionpi.com/forum/viewtopic.php?t=4196&start=10#p15055

**Comment by floion** [comment]
@wickywaka so Kunbus has ongoing work kernel wise for the connect 4?

**Comment by wickywaka** [comment]
> @wickywaka so Kunbus has ongoing work kernel wise for the connect 4?

They are in contact with balena from what I know. Don't know more than that.

May be this PR https://github.com/balena-os/balena-raspberrypi/pull/1090 fixes some of the issues where my changes to revpi4 machines were taking effects. We can have a look at this this week or next week.

**Pull request closed without merging**
