### PR TITLE
layers/meta-balena: Update to v2.107.46

### PR DESCRIPTION
**Pull request by alexgg**
Update meta-balena from 2.107.43 to 2.107.46

Changelog-entry: Update meta-balena from v2.107.43 to v2.107.46

### CODE REVIEW

**Comment by alexgg** [comment]
lgtm

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by rcooke-warwick** [comment]
@resin-jenkins retest this please

**Comment by rcooke-warwick** [comment]
this PR is having problems with the fin's ability to connect to the testbots wifi AP - I think we've had this problem before, might be worth investigating if this fix is relevant: https://github.com/balena-os/balena-raspberrypi/pull/910

**Comment by alexgg** [comment]
Backported https://github.com/balena-os/balena-raspberrypi/pull/910 to the ESR branch

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
The validation of this PR was not passing for the fin so this was never merged. Now 2023.4 is out so there is no need for this update.

**Pull request closed without merging**
