### PR TITLE
Release v2.67.3+rev1 and switch to dunfell

### PR DESCRIPTION
**Pull request by floion**

### CODE REVIEW

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by thgreasi** [comment]
See: https://github.com/balena-io/balena-io/issues/2334

**Comment by acostach** [comment]
@resin-jenkins retest

**Comment by acostach** [comment]
@balena-ci retest

**Review by acostach — APPROVED** [review]

**Pull request merged**
