### PR TITLE
bluez5: Use bluez5 v5.58 from meta-balena

### PR DESCRIPTION
**Pull request by majorz**
Removed are the bluez5 v5.56 definitions together with two patches
that were backported here and are already included of v5.58. The only
nebra-hnt specific file left is the main.conf that sets DeviceID to
false.

Change-type: patch
Signed-off-by: Zahari Petkov <zahari@balena.io>

### CODE REVIEW

**Review by alexgg — COMMENTED** [review]
@majorz what about setting DeviceID as false in meta-balena too? afair, this is just going back to previous behavour.

**Comment by majorz** [comment]
> @majorz what about setting DeviceID as false in meta-balena too? afair, this is just going back to previous behavour.

@alexgg That makes sense, I will look at it now and create a new meta-balena PR for this.

**Comment by KillingJacky** [comment]
Need this to be merged into RPi 4 ASAP, the builtin DIS in bluez with only the PNP ID is crappy and it's stopping us registering a complete DIS.

**Comment by alexgg** [comment]
@balena-ci rebase

**Review by alexgg — APPROVED** [review]
@joehounsham @floion the only customization for the `nebra-hnt` device type is a custom patch to set policies on the hostOS d-bus - with the d-bus block (https://github.com/balenablocks/dbus) and the work @jakogut has done with Helium, they should be able to move to a standard DT and stop supporting the custom one.

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Pull request merged**
