### PR TITLE
Enable firmware compression for cm4-ioboard and pi400

### PR DESCRIPTION
**Pull request by klutchell**
See: https://github.com/balena-os/balena-raspberrypi/pull/705#issuecomment-920779168

PR to test changes for this JF ticket: https://jel.ly.fish/support-thread-discourse-346995

### CODE REVIEW

**Comment by mtoman** [comment]
@resin-jenkins retest this please

**Comment by keenanjohnson** [comment]
Thanks for working on this all! let me know if I can support in anyway as this is really helpful for an open-source project I'm working on!

**Comment by klutchell** [comment]
@jakogut we are still hung up on the `iwlwifi_firmware_clean` task right? Any ideas to progress?

It seems like any further fakeroot steps involving linux-firmware will fail if any wifi firmware is cleaned. For now I've disabled cleaning any modules but that's more of a workaround and might not actually fit on flash.

**Comment by jakogut** [comment]
@klutchell I have a PR that turns this error into a nondeterministic metadata error, which is at least reproducible locally. Once we solve that, the branch can be merged, I think.

**Comment by jakogut** [comment]
@klutchell Yeah, that's the one.

**Comment by klutchell** [comment]
@acostach @floion @alexgg Do any of your foresee any negative impact from restoring all iwlwifi modules in addition to the ones that were removed for space reasons on these two devices?

Could we put a pi400 or cm4 online so I could test these changes?

I haven't compared the size difference of the firmware directory yet, but it's on my list.

**Comment by keenanjohnson** [comment]
I can put a CM4 online if that's helpful for you @klutchell!

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
> I can put a CM4 online if that's helpful for you @klutchell!

Thanks @keenanjohnson but there's a chance it won't boot after the update and it will have to rollback. I'll have David send you a raw image for your own testing instead, so you can reflash as needed.

**Comment by floion** [comment]
@klutchell I created another PR with a mix of you commits and another one that enables compression for all Pi 4 based boards: https://github.com/balena-os/balena-raspberrypi/pull/713

**Comment by klutchell** [comment]
Superseded by https://github.com/balena-os/balena-raspberrypi/pull/713

**Pull request closed without merging**
