### PR TITLE
layers/meta-balena: Update to v5.0.12

### PR DESCRIPTION
**Pull request by alexgg**
Update meta-balena from 5.0.11 to 5.0.12

Changelog-entry: Update meta-balena from v5.0.11 to v5.0.12

### CODE REVIEW

**Comment by alexgg** [comment]
lgtm

**Comment by alexgg** [comment]
`testbot-raspberrypi3-64`:
* os: PASS
* cloud: FAILED
```
jenkins-leviathan-v2-template-43848-client-1  | [2024-03-12T15:05:39.763Z][2f984ac-cloud] An error has occurred executing internal preload command 'get_image_info':
jenkins-leviathan-v2-template-43848-client-1  | [2024-03-12T15:05:39.763Z][2f984ac-cloud] {"command":"get_image_info","parameters":{}}
jenkins-leviathan-v2-template-43848-client-1  | 
jenkins-leviathan-v2-template-43848-client-1  | Status code: 1
jenkins-leviathan-v2-template-43848-client-1  | Error: Traceback (most recent call last):
jenkins-leviathan-v2-template-43848-client-1  | [2024-03-12T15:05:39.763Z][2f984ac-cloud]   File "/usr/src/app/preload.py", line 978, in <module>
jenkins-leviathan-v2-template-43848-client-1  |     result = method(**data.get("parameters", {}))
jenkins-leviathan-v2-template-43848-client-1  |   File "/usr/src/app/preload.py", line 927, in get_image_info
jenkins-leviathan-v2-template-43848-client-1  |     init()
jenkins-leviathan-v2-template-43848-client-1  |   File "/usr/src/app/preload.py", line 945, in init
jenkins-leviathan-v2-template-43848-client-1  |     PARTITIONS_CACHE[None] = prepare_global_partitions()
jenkins-leviathan-v2-template-43848-client-1  |   File "/usr/src/app/preload.py", line 137, in prepare_global_partitions
jenkins-leviathan-v2-template-43848-client-1  |     return get_partitions(IMAGE)
jenkins-leviathan-v2-template-43848-client-1  |   File "/usr/src/app/preload.py", line 126, in get_partitions
jenkins-leviathan-v2-template-43848-client-1  |     return {p.label: p for p in PartitionTable(image).partitions if p.label}
jenkins-leviathan-v2-template-43848-client-1  |   File "/usr/src/app/preload.py", line 456, in __init__
jenkins-leviathan-v2-template-43848-client-1  |     part = Partition(self, number, **partition_data)
jenkins-leviathan-v2-template-43848-client-1  |   File "/usr/src/app/preload.py", line 241, in __init__
```
* HUP: FAILED
```
jenkins-leviathan-v2-template-43848-client-1  | [2024-03-12T15:15:28.529Z][2f984ac-hup]             # Running: hostapp-update -f /mnt/data/resin-data/image-hhwqeiwl
jenkins-leviathan-v2-template-43848-client-1  | [2024-03-12T16:05:31.802Z][2f984ac-hup]             # Finished HUP
jenkins-leviathan-v2-template-43848-client-1  | [2024-03-12T16:05:33.770Z][2f984ac-hup] All configured authentication methods failed
```

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
Passed:

* test-raspberrypi3-64
* test-raspberrypi4-64

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by rcooke-warwick** [comment]
@alexgg I have marked the yocto builds and failed leviathan  for the pi0 and pi3 (just retried) as keep forever, so we will always be able to retry through jenkins UI and not have to retry for all 4 devices types through a retest command

**Comment by rcooke-warwick** [comment]
pi3 is failing due to a worker having a full data parition, purging then will retry

**Comment by rcooke-warwick** [comment]
pi 0 passes

**Pull request merged**
