### PR TITLE
Add support for the TECHBASE NPE X500 M3 board (CM3 based)

### PR DESCRIPTION
**Pull request by adolfogc**
Related issue: #292

### CODE REVIEW

**Comment by floion** [comment]
@resin-jenkins ok to test

**Comment by floion** [comment]
Hi @adolfogc , thank you for the contribution.

Can you redo the PR as per the commit guidelines from https://github.com/balena-os/balena-raspberrypi#pull-requests ?

Also, can you try to split the changes more like 1 commit per changed file?
Also, can you mark the board as `community` in the respective .coffee file, like seen in https://github.com/balena-os/balena-jetson-tx2/blob/master/n510-tx2.coffee#L19?

**Comment by adolfogc** [comment]
Hi @floion, thanks for the review. I've made the changes as requested.

**Comment by floion** [comment]
@resin-ci retest

**Comment by floion** [comment]
Hi @adolfogc there is one commit which has the commit header on more than 1 line. Can you redo it to only be in 1 line and no longer than 72 chars?
> The header of each commit must not exceed 72 characters in length and must be in 1 line only.

**Comment by adolfogc** [comment]
Hi @floion, I've fixed the issue with the commit headers.

**Comment by floion** [comment]
@resin-ci retest

**Comment by floion** [comment]
Hi @adolfogc we still need some changes.

> The header and the subject of each commit must be separated by an empty line.

Can you make sure all your commits follow this rule please?

**Comment by adolfogc** [comment]
> Can you make sure all your commits follow this rule please?

Hi @floion, I just checked using `git log`, and there's an empty line separating the headers from the bodies, so I'm not sure why the CI check is failing with regards to this.

**Comment by floion** [comment]
@adolfogc the problem is that there's a new line between `Changelog-entry` and `Signed-off-by` for the commits. Can you remove that empty line in between?

**Comment by adolfogc** [comment]
@floion I have rebased and corrected the issue of the blank space between those lines.

**Comment by adolfogc** [comment]
@resin-ci retest

**Comment by adolfogc** [comment]
@resin-ci retest

**Comment by floion** [comment]
Thanks @adolfogc . Have you done other changes? The yocto build fails now (it worked before):

>  make[3]: *** No rule to make target 'arch/arm/boot/dts/overlays/npe-x500-m3.dtbo'.  Stop.
| arch/arm/Makefile:345: recipe for target 'overlays/npe-x500-m3.dtbo' failed
| make[2]: *** [overlays/npe-x500-m3.dtbo] Error 2
| Makefile:146: recipe for target 'sub-make' failed
| make[1]: *** [sub-make] Error 2
| Makefile:24: recipe for target '__sub-make' failed
| make: *** [__sub-make] Error 2
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.

**Comment by adolfogc** [comment]
@floion No I haven't, I just amended the commit messages. Is there a way to re-run Jenkins?

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by adolfogc** [comment]
@floion It worked. I think it was because of my force pushes; each too close to one another in time.

**Comment by floion** [comment]
@adolfogc it failed in the same way

**Pull request merged**
