### PR TITLE
layers/meta-balena: Update to v5.1.58

### PR DESCRIPTION
**Pull request by alexgg**
Update meta-balena from 5.1.55 to 5.1.57

Changelog-entry: Update meta-balena from v5.1.55 to v5.1.57

### CODE REVIEW

**Comment by alexgg** [comment]
lgtm

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by jakogut** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
Passed:

- test-raspberrypi3 
- test-raspberrypi3-64

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by klutchell** [comment]
`test-raspberrypi3-64` failed the preload test and is likely a fluke
```
jenkins-leviathan-v2-template-54011-client-1  | Retrying (count=10) /sbin/losetup -f --show --offset 4194304 --sizelimit 41943040 /img/balena.img False
jenkins-leviathan-v2-template-54011-client-1  | Hint: If using a Virtual Machine, consider increasing the number of processors.
jenkins-leviathan-v2-template-54011-client-1  | If using Docker Desktop for Windows or macOS, it may require restarting.
```

**Comment by alexgg** [comment]
`test-raspberrypi ` failures:

HUP:
```
jenkins-leviathan-v2-template-54013-client-1  | [2024-06-18T15:09:54.145Z][7c68847-hup]         not ok 1 - Should detect cd6682b.local on local network and establish tunnel
```
OS:
```
jenkins-leviathan-v2-template-54013-client-1  | [2024-06-18T15:34:17.837Z][fe2b1d3-os]     not ok 2 - Device 5a26794.local should be reachable over local SSH connection
```
Cloud:
```
jenkins-leviathan-v2-template-54013-client-1  | [2024-06-18T15:52:24.535Z][fe2b1d3-cloud] 500 - "<!DOCTYPE html><html><head><meta charset=\"utf8\"><title>balena.io Device Public URLs</
```

None of them actually started running tests on device so there might be something wrong with the device in the rig. We should run an e2e test on it.

**Comment by alexgg** [comment]
I re-ran `test-raspberrypi3 `

**Comment by alexgg** [comment]
Re-ran all individual tests

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
Restarted the tests.
Also, marked the builds in Jenkins as to be kept forever so we don't have to keep restarting the builds after 24 hours. When this PR is merged we should unmark these builds as to be kept forever,

**Comment by alexgg** [comment]
Passed:
* test-raspberrypi3 
* test-raspberrypi3-64
* test-raspberrypi4-64

Just re-tried `test-raspberrypi` that failed to see the device after programming.

Please do not retest all as we just need the RPI to pass.

**Comment by alexgg** [comment]
I removed the `keep this build forever` from the builds.

**Pull request merged**
