### PR TITLE
layers/meta-balena: Update to v2.107.42

### PR DESCRIPTION
**Pull request by alexgg**
Update meta-balena from 2.107.40 to 2.107.41

This brings in a patch to the tests that will allow the RPI0 to be released.

Changelog-entry: Update meta-balena from v2.107.40 to v2.107.41
Signed-off-by: Alex Gonzalez <alexg@balena.io>

### CODE REVIEW

**Comment by alexgg** [comment]
@balena-ci I self-certify!

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
lgtm

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
Failure for RPI0:
```
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.587Z][7c68847-os]     # Subtest: Engine healthcheck tests
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.587Z][7c68847-os]         # Subtest: Engine watchdog recovery
jenkins-leviathan-v2-template-13002-client-1  |             not ok 1 - Watchdog timeout should have been decreased
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.588Z][7c68847-os]               ---
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.588Z][7c68847-os]               found: ""
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.588Z][7c68847-os]               wanted: "0"
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.588Z][7c68847-os]               compare: ===
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.588Z][7c68847-os]               at:
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.588Z][7c68847-os]                 line: 26
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.588Z][7c68847-os]                 column: 10
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.589Z][7c68847-os]                 file: /data/suite/tests/engine-healthcheck/index.js
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.589Z][7c68847-os]                 type: Proxy
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.589Z][7c68847-os]                 function: run
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.589Z][7c68847-os]               stack: |
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.589Z][7c68847-os]                 Proxy.run (/data/suite/tests/engine-healthcheck/index.js:26:10)
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.589Z][7c68847-os]               source: |
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.589Z][7c68847-os]                 				// Decrease the watchdog timeout to make the test run quicker.
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.590Z][7c68847-os]                 				test.is(
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.590Z][7c68847-os]                 ---------^
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.590Z][7c68847-os]                 					await this.worker.executeCommandInHostOS(
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.590Z][7c68847-os]                 						`mkdir -p /run/systemd/system/balena.service.d &&
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.590Z][7c68847-os]               ...
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.605Z][7c68847-os] 
jenkins-leviathan-v2-template-13002-client-1  | [2023-02-06T15:20:45.605Z][7c68847-os]             Bail out! Watchdog timeout should have been decreased
```

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
@floion  `test-raspberrypi ` has finally passed for this PR - I'll go ahead and force merge as that will hopefully release an ESR for the RPI0. The rest of the DT already have ESR releases so it's not a problem that their tests are flaky.

**Comment by floion** [comment]
@alexgg all looks good, seems like 2023.1.1 was done for rpi0 after you force merged the PR

**Pull request merged**
