### PR TITLE
nebra-hnt: Remove this device type

### PR DESCRIPTION
**Pull request by floion**
The customer does not use this device type anymore and
instead is using raspberrypi3-64.

Changelog-entry: Remove the nebra-hnt device type as it's not used anymore
Signed-off-by: Florin Sarbu <florin@balena.io>

### CODE REVIEW

**Comment by floion** [comment]
As per https://www.flowdock.com/app/rulemotion/resin-devices/threads/xZAVwLsKNqbzXtH1aCBat4yEvxR

**Comment by floion** [comment]
@balena-ci I self-certify!

**Comment by vipulgupta2048** [comment]
@balena-ci retest

**Comment by vipulgupta2048** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by vipulgupta2048** [comment]
@resin-jenkins retest this please

**Pull request merged**
