### PR TITLE
[2024.7] Update meta-balena to v5.2.13

### PR DESCRIPTION
**Pull request by alexgg**
Update meta-balena from 5.2.10 to 5.2.12

Changelog-entry: Update meta-balena from v5.2.10 to v5.2.12

### CODE REVIEW

**Comment by rcooke-warwick** [comment]
retried the other PR first

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by rcooke-warwick** [comment]
@resin-jenkins retest this please

**Comment by rcooke-warwick** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
lgtm

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by rcooke-warwick** [comment]
will retry now through jenkins UI, do not retry through the comments here plz

**Pull request merged**
