### PR TITLE
layers/meta-balena: Update to v2.71.0

### PR DESCRIPTION
**Pull request by acostach**
Update meta-balena from 2.69.1 to 2.71.0

Changelog-entry: Update meta-balena from v2.69.1 to v2.71.0
Signed-off-by: Alexandru Costache <alexandru@balena.io>

### CODE REVIEW

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by floion** [comment]
Superseded by https://github.com/balena-os/balena-raspberrypi/pull/610

**Pull request closed without merging**
