### PR TITLE
add balena-fin overlay for raspberrypi3-64

### PR DESCRIPTION
**Pull request by shawaj**
add balena-fin overlay to the 64 bit raspberry pi 3 image

Change-type: patch
Signed-off-by: Aaron Shaw <aaron@balena.io>

### CODE REVIEW

**Comment by majorz** [comment]
I am not sure adding the dtbo for the RPi 4/64bit is the correct way to address this as the WiFi driver for the Fin will not be included + probably some other patches and tweaks.

**Comment by shawaj** [comment]
@majorz I'm not sure I understand your meaning?

Currently there is no support for a cm3 in the raspberrypi3-64 image. And the fin is only supported in fincm3 image.

I guess we could create a fincm3-64 image but it means maintaining another image for 64 bit use cases. I guess it is relatively trivial.

But adding the dtb for fin to the Raspberry Pi 3 image seems to make sense as well in my opinion just because the overlay can

**Comment by shawaj** [comment]
Oops closed by accident

**Comment by majorz** [comment]
Having a generic support for CM3(+) on a RPi 3 image is a different concept than supporting a specific board like the balenaFin.

Probably a different device tree overlay needs to be added for generic compute module support rather than the specific device tree configuration for the balenaFin. I see a few CM3 overlays available in the raspberrypi kernel source repo.

Specific boards has extra features that are both referenced in their overlays and other settings and those will need extra device types.

Also it is unclear what the intent of the PR is as it does not contain detailed explanation on what it is trying to solve nor it does link to a specific issue. What do we want to solve more specifically with it?

**Comment by majorz** [comment]
I now saw you added another PR on this upstream in the meta-raspberrypi repository. That should be the direction for generic CM3 support.

If a specific customer really needs a balenaFin 64bit support we may add a new fincm3-64 device type. Adding here the overlay, which references configuration of the fincm3 device type like including proprietary wifi driver settings, does not seem the right place.

**Comment by shawaj** [comment]
@majorz sorry yeah I should have mentioned #486 was where this originated from essentially. But in my testing with Fin the 64bit use case was not supported either - which just felt a bit wrong to me that we don't support 64 bit on our own hardware.

Understand what you are saying though - perhaps this is too much of a quick and dirty approach. Just thought it was a simple and quick way to support a 64 bit use case on Fin without having to spin up a fincm3-64 device type, which is more involved.

I will move to a product call perhaps so we can discuss further. Maybe there is some reason we decided against fincm3-64 already that I am not aware of.

Thanks for your thoughts in any case!

**Comment by majorz** [comment]
I think for the most part the reason is that 64bit support initially was nonexistent, then buggy and now there is not a high demand.

**Comment by shawaj** [comment]
Makes sense!

**Comment by shawaj** [comment]
Closing based on above discussion

**Pull request closed without merging**
