### PR TITLE
removed the removal of the patch for the kernel BT driver.

### PR DESCRIPTION
**Pull request by hicklin**
When enabling the `uart3` DT overlay, bluetooth sometimes fails to come up on reboots. The following observations were made on the Balena OS `v2.89.3+rev1` for the Raspberry Pi CM4. A test program has been written that repeatedly checks the state of the bluetooth and reboots the RPi. In the following, I will note the percentage success rate and the number of reboots with `N=xxx`.

In the default configuration, i.e. no extra DT overlays. The bluetooth comes up 100 % of the time `N=90`.

When the `uart3` DT overlay was added, bluetooth came up 45% of the time `N=2420`. We have posted about this issue on the [Raspberry Pi forum](https://forums.raspberrypi.com/viewtopic.php?t=322266#p1942759). Details of the possible reasons and solutions are listed there. The main solution was to switch on the kernel BT driver via the DT param `krnbt=on`. This improved the success rate with BT coming up 95 % of the time `N=611`. However, this is not 100 %.

The kernel logs suggested that there was a missing patch file.

```
kern  :err   : [    5.537772] Bluetooth: hci0: BCM: firmware Patch file not found, tried:
kern  :err   : [    5.537784] Bluetooth: hci0: BCM: 'brcm/BCM4345C0.hcd'
kern  :err   : [    5.537790] Bluetooth: hci0: BCM: 'brcm/BCM.hcd'
```

After copying the [`BCM4345C0.hcd`](https://github.com/RPi-Distro/bluez-firmware/blob/master/broadcom/BCM4345C0.hcd) file in `/lib/firmware/brcm`, the kernel logs didn't show any errors and the bluetooth came up 100 % of the time `N=659`.

Interestingly, the `BCM4345C0.hcd` file exists in a raspberry Pi 4.

### The solution

So the solution is to have this file copied in the built OS. Looking in the `meta-raspberrypi` and `meta-balena-raspberrypi` layers it seems that `meta-raspberrypi` installs this file in the [bluez-firmware-rpidistro recipe](https://github.com/agherzan/meta-raspberrypi/blob/honister/recipes-kernel/bluez-firmware-rpidistro/bluez-firmware-rpidistro_git.bb)  line 52. This recipe provides the package `bluez-firmware-rpidistro-bcm4345c0-hcd` which installs the `BCM4345C0.hcd` file. The `meta-balena-raspberrypi` recipe [`packagegroup-balena-connectivity.bbappend`](https://github.com/balena-os/balena-raspberrypi/blob/master/layers/meta-balena-raspberrypi/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend), doesn't not install this package for the PRi CM4 (see lines 73 and 80).

By removing line 73, the `BCM4345C0.hcd` was installed in the built OS.

Please let me know if there is any reason why this file was removed for the RPi CM4 build.

### CODE REVIEW

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
Hi @hicklin and thanks for your PR. That list of firmware files was removed for the newly added boards at that point due to space constraints, let's see if we can add it back now.

Meanwhile, can you please modify the commit message according to the commit guidelines so it can pass the versioning check? For instance:
```
packagegroups: Include BCM4345C0 firmware for CM4, Pi4, Pi400

Changelog-entry: packagegroups: Include BCM4345C0 firmware for CM4, Pi4, Pi400
Signed-off-by: Your Name <address@provider.com>
```

**Comment by acostach** [comment]
Hi @hicklin , can you please rebase this on top of master and create a single commit for this change? For now there are 4 commits and since it's just one line it can be added trough one commit that has Changelog-entry and Signed-off-by:
```
Commits on Feb 14, 2022

[removed the removal of the patch for the kernel BT driver.](https://github.com/balena-os/balena-raspberrypi/pull/786/commits/63bd7f51f3739a97847c3e4ea06a964e2928c3a0)
    William Hicklin committed 21 hours ago

Commits on Feb 15, 2022

[Merge branch 'master' into fix_BT_reliability_on_RPi_CM4](https://github.com/balena-os/balena-raspberrypi/pull/786/commits/fc9e9495b0a330cc1a08090b1f48dec12ef7cefc)
    @[acostach](https://github.com/hicklin/balena-raspberrypi/commits?author=acostach)
    acostach committed 4 hours ago

[packagegroups: Include BCM4345C0 firmware for CM4, Pi4, Pi400](https://github.com/balena-os/balena-raspberrypi/pull/786/commits/ed9b0ef3c23adf13ca8d72bf45a4937b3a404117)
William Hicklin committed 3 hours ago

[Merge branch 'fix_BT_reliability_on_RPi_CM4' of github.com:hicklin/ba…](https://github.com/balena-os/balena-raspberrypi/pull/786/commits/0261dcdecc07a8063972d90be15046ade2d7ade2)
William Hicklin committed 3 hours ago
```

 You can then force push the branch in your repository and it should be automatically updated in this PR. Thanks

**Comment by hicklin** [comment]
Hi @[acostach](https://github.com/acostach), it should all be neatly compressed in one commit now.

**Comment by acostach** [comment]
@hicklin sorry, it seems that 3 more commits were added: ` William Hicklin and others added 7 commits 11 minutes ago` and the branch has conflicts that can't be resolved by github. Can you try updating the master branch in your forked repo so that it matches the SHA of the current master branch and then apply your commit? Alternatively you can open a new PR to replace this one.

**Comment by hicklin** [comment]
Opened another PR with a clean commit.

**Pull request closed without merging**
