### PR TITLE
u-blox-modeswitch: remove recipe

### PR DESCRIPTION
**Pull request by markcorbinuk**
Remove the recipe for u-blox-modeswitch. It is generic and will be added via the meta-balena layer instead.

Change-type: patch
Connects-to: #1789 (in meta-balena)
Signed-off-by: Mark Corbin <mark@balena.io>

### CODE REVIEW

**Comment by markcorbinuk** [comment]
@balena-os/balena-devices-team This PR will need to be merged at the point when balena-raspberrypi gets updated to use a release of meta-balena that contains this update https://github.com/balena-os/meta-balena/pull/1962

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by markcorbinuk** [comment]
@balena-ci retest this please

**Comment by markcorbinuk** [comment]
@balena-ci retest this please

**Comment by markcorbinuk** [comment]
@resin-jenkins retest this please

**Comment by markcorbinuk** [comment]
@balena-ci version

**Review by alexgg — APPROVED** [review]

**Comment by alexgg** [comment]
@balena-ci retest

**Comment by markcorbinuk** [comment]
@balena-ci rebase

**Comment by markcorbinuk** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@markcorbinuk a Changelog-entry is needed in the commit message for versionist to trigger the checks.

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by markcorbinuk** [comment]
@acostach I've never had an issue with PRs on meta-balena where my commits don't have a Changelog-entry.
The development guidelines say that it is optional, so I don't add it. Does it need to be added to the process as 'Required'?

**Comment by acostach** [comment]
@markcorbinuk, from https://github.com/balena-os/balena-raspberrypi/blob/master/README.md#pull-requests 

"_Every pull request **must** contain at least one commit annotated with the Changelog-entry footer. The messages contained in these footers will be used to automatically fill the changelog on every new version._"

**Comment by markcorbinuk** [comment]
@acostach from https://github.com/balena-io/process/blob/master/process/Commit_and_PR_Guidelines.md

"_Commits marked with the Change-type tag will have their subject added as an entry in the generated CHANGELOG.md. If you want to override this default behavior and add your own changelog entry instead, you can use the **optional** Changelog-Entry: <custom changelog entry> tag in Change-type-tagged commits._"

I didn't realise that there were different rules for different repositories.

**Comment by acostach** [comment]
thanks @markcorbinuk, I added a [note](https://github.com/balena-io/process/issues/241#issuecomment-722367910) regarding this in the existing docs issue.

**Comment by markcorbinuk** [comment]
@resin-jenkins retest this please

**Comment by acostach** [comment]
@balena-ci retest

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by markcorbinuk** [comment]
@resin-jenkins test this please

**Comment by markcorbinuk** [comment]
@balena-ci retest

**Pull request merged**
