### PR TITLE
Fix kernel configuration checks warnings

### PR DESCRIPTION
**Pull request by alexgg**
Depends-on: https://github.com/balena-os/meta-balena/pull/3376

### CODE REVIEW

**Review by klutchell — APPROVED** [review]

**Comment by alexgg** [comment]
Depends on https://github.com/balena-os/balena-raspberrypi/pull/1102

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
Depends on https://github.com/balena-os/balena-raspberrypi/pull/1107

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Pull request merged**
