### PR TITLE
Jakogut/fin i2c pullup

### PR DESCRIPTION
**Pull request by jakogut**

### CODE REVIEW

**Comment by jakogut** [comment]
Relevant context

https://jel.ly.fish/thread-a7332c70-020b-4ce5-9239-1576a146d7e9

**Review by hraftery — APPROVED** [review]
Looks great. I checked that the patch changes are valid against the [RPi 5.10.y](https://github.com/raspberrypi/linux/tree/rpi-5.10.y/arch/arm/boot/dts/overlays) branch (and the 5.15.y branch out of curiosity) and all looks good. I see now that this is sufficient to make the changes we want.

Just one suggestion that doesn't prevent approval. In the Improvement I suggested:

> While we’re making improvements, `gpios` is deprecated in `i2c-gpio`, so I think we may as well switch to the newer, self-documenting properties:
> 
> `sda-gpios = <&gpio 43 (GPIO_ACTIVE_HIGH|GPIO_OPEN_DRAIN|GPIO_PULL_UP)>;`
> `scl-gpios = <&gpio 42 (GPIO_ACTIVE_HIGH|GPIO_OPEN_DRAIN|GPIO_PULL_UP)>;`

I think this is still true, but if you'd prefer a minimal change instead then so be it.

**Comment by jakogut** [comment]
@hraftery I can add that as another commit, but I like to separate style changes from functional changes.

**Comment by rcooke-warwick** [comment]
@balena-ci rebase

**Comment by majorz** [comment]
@balena-ci rebase

**Review by majorz — APPROVED** [review]
I checked all the relevant information surrounding this issue and approving it as it seems to have been staled. We also need this so that we may continue looking into the SDIO improvements that involve other GPIOs on the same bank.

**Review by alexgg — APPROVED** [review]
lgtm, added `Changelog-entry` to commit message to make versionbot happy.

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by majorz** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins ok to test

**Comment by floion** [comment]
@resin-jenkins test this please

**Pull request merged**
