### PR TITLE
meta-balena-raspberry: Rename resin-extra-udev-rules

### PR DESCRIPTION
**Pull request by alexgg**
This recipe has been renamed in upstream meta-balena.

Change-type: patch
Signed-off-by: Alex Gonzalez <alexg@balena.io>

### CODE REVIEW

**Comment by floion** [comment]
@alexgg is this needing https://github.com/balena-os/meta-balena/pull/2765 to be merged first?

**Comment by alexgg** [comment]
hey @floion it needs https://github.com/balena-os/meta-balena/pull/2756/

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
Rebased over https://github.com/balena-os/balena-raspberrypi/pull/941, can close once that merges.

**Comment by alexgg** [comment]
Once again rebased over #941, can close once that merges.

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by majorz** [comment]
@balena-ci rebase

**Pull request merged**
