### PR TITLE
conf/layer: Add vc4-kms-dsi-7inch overlay

### PR DESCRIPTION
**Pull request by acostach**
Changelog-entry: conf/layer: Add vc4-kms-dsi-7inch overlay
Signed-off-by: Alexandru Costache <alexandru@balena.io>

### CODE REVIEW

**Review by floion — APPROVED** [review]

**Comment by floion** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
Requested in internal thread https://www.flowdock.com/app/rulemotion/r-beginners/threads/3pG-g-iVG1a1XkYmPNpMdSbIIka

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@balena-ci rebase

**Pull request merged**
