### PR TITLE
Switch Rpi boards to Honister

### PR DESCRIPTION
**Pull request by acostach**

### CODE REVIEW

**Review by floion — APPROVED** [review]

**Comment by acostach** [comment]
Hi @jakogut , I've included the -Os flag for the Pi3-64 and Pi4-64 so that Honister can fit in their current rootfs space, as per your investigation in https://github.com/balena-os/meta-balena/pull/2411.  What I'm not sure is whether CONFIG_SLOB is needed and for what exactly. I saw you included it in your PR so maybe you recall what was the reason for using it and whether we should include it for these Pis too. Thanks

**Comment by jakogut** [comment]
> Hi @jakogut , I've included the -Os flag for the Pi3-64 and Pi4-64 so that Honister can fit in their current rootfs space, as per your investigation in [balena-os/meta-balena#2411](https://github.com/balena-os/meta-balena/pull/2411). What I'm not sure is whether CONFIG_SLOB is needed and for what exactly. I saw you included it in your PR so maybe you recall what was the reason for using it and whether we should include it for these Pis too. Thanks

@acostach, From the Kconfig description for `CONFIG_SLOB`:

> SLOB replaces the stock allocator with a drastically simpler                                                                                                                                                                             
allocator. SLOB is generally more space efficient but                                                                                                                                                                                    
does not perform as well on large systems.

So this is unnecessary and probably even detrimental on larger systems, but can slightly reduce the kernel size at the cost of performance.

**Comment by acostach** [comment]
> So this is unnecessary and probably even detrimental on larger systems, but can slightly reduce the kernel size at the cost of performance.

Thank you Joseph, I was suspecting it helped reduce the kernel size but wanted to confirm this with you. In this case we can skip including it for now.

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@resin-jenkins test this please

**Pull request merged**
