### PR TITLE
meta-balena-raspberrypi:layer.conf: Add PoE+ overlay to rootfs

### PR DESCRIPTION
**Pull request by floion**
Include the PoE+ overlay to rootfs for supporting this newer hat

Changelog-entry: Add Raspberry Pi PoE+ overlay to rootfs
Signed-off-by: Florin Sarbu <florin@balena.io>

### CODE REVIEW

**Comment by floion** [comment]
@balena-ci I self-certify!

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
@balena-ci rebase

**Pull request merged**
