### PR TITLE
[2024.4] layers/meta-balena: Update to v5.1.62

### PR DESCRIPTION
**Pull request by alexgg**
Update meta-balena from 5.1.58 to 5.1.62

Changelog-entry: Update meta-balena from v5.1.58 to v5.1.62

### CODE REVIEW

**Comment by alexgg** [comment]
lgtm

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by joshbwlng** [comment]
@resin-jenkins retest this please

**Comment by rcooke-warwick** [comment]
all who see - please do not retest this, I'm using the jenkins UI to avoid having to re test all devices

**Pull request merged**
