### PR TITLE
linux-raspberrypi: Update from 5.10.83 to 5.10.95

### PR DESCRIPTION
**Pull request by acostach**
Changelog-entry: linux-raspberrypi: Update from 5.10.83 to 5.10.95
Signed-off-by: Alexandru Costache <alexandru@balena.io>

### CODE REVIEW

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Comment by acostach** [comment]
@balena-ci I self-certify!

**Comment by rcooke-warwick** [comment]
@resin-jenkins retest this please

**Comment by acostach** [comment]
@balena-ci rebase

**Pull request merged**
