### PR TITLE
Update to kernel 5.10.31

### PR DESCRIPTION
**Pull request by floion**

### CODE REVIEW

**Comment by klutchell** [comment]
Supersedes https://github.com/balena-os/balena-raspberrypi/pull/604

**Comment by Razikus** [comment]
I have problem to build this on my own
I've got plenty of meesages when im trying to build raspberrypicm4-ioboard

`ERROR: kernel-headers-test-1.0-r0 do_compile: Execution of '/home/adam/balena/build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/temp/run.do_compile.113305' failed with exit code 2:
The command '/bin/sh -c ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_source/*/build/ M=/usr/src/app/example_module_headers_src' returned a non-zero code: 2
WARNING: exit code 2 from a shell command.

ERROR: Logfile of failure stored in: /home/adam/balena/build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/temp/log.do_compile.113305
Log data follows:
| DEBUG: Executing shell function do_compile
| The command '/bin/sh -c ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_source/*/build/ M=/usr/src/app/example_module_headers_src' returned a non-zero code: 2
| WARNING: exit code 2 from a shell command.
| ERROR: Execution of '/home/adam/balena/build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/temp/run.do_compile.113305' failed with exit code 2:
| The command '/bin/sh -c ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_source/*/build/ M=/usr/src/app/example_module_headers_src' returned a non-zero code: 2
| WARNING: exit code 2 from a shell command.
| 
ERROR: Task (/home/adam/balena/build/../layers/meta-balena/meta-balena-common/recipes-kernel/linux/kernel-headers-test.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 4155 tasks of which 3069 didn't need to be rerun and 1 failed.
`

**Comment by floion** [comment]
> I have problem to build this on my own
> I've got plenty of meesages when im trying to build raspberrypicm4-ioboard
> 
> ```
> ERROR: kernel-headers-test-1.0-r0 do_compile: Execution of '/home/adam/balena/build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/temp/run.do_compile.113305' failed with exit code 2:
> The command '/bin/sh -c ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_source/*/build/ M=/usr/src/app/example_module_headers_src' returned a non-zero code: 2
> WARNING: exit code 2 from a shell command.
> 
> ERROR: Logfile of failure stored in: /home/adam/balena/build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/temp/log.do_compile.113305
> Log data follows:
> | DEBUG: Executing shell function do_compile
> | The command '/bin/sh -c ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_source/*/build/ M=/usr/src/app/example_module_headers_src' returned a non-zero code: 2
> | WARNING: exit code 2 from a shell command.
> | ERROR: Execution of '/home/adam/balena/build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/temp/run.do_compile.113305' failed with exit code 2:
> | The command '/bin/sh -c ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_source/*/build/ M=/usr/src/app/example_module_headers_src' returned a non-zero code: 2
> | WARNING: exit code 2 from a shell command.
> | 
> ERROR: Task (/home/adam/balena/build/../layers/meta-balena/meta-balena-common/recipes-kernel/linux/kernel-headers-test.bb:do_compile) failed with exit code '1'
> NOTE: Tasks Summary: Attempted 4155 tasks of which 3069 didn't need to be rerun and 1 failed.
> ```
> 
> Is there any docker version required to build it?
> Problematic thing is here
> layers/meta-balena/meta-balena-common/recipes-kernel/linux/files/Dockerfile
> 
> Ah you just pushed something, but idk if its relevant
> 
> Investigating more - ther eis a problem with
> Step 12/14 : RUN ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_source/*/build/ M=/usr/src/app/example_module_headers_src
> 
> ```
> Step 12/14 : RUN ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_source/*/build/ M=/usr/src/app/example_module_headers_src
>  ---> Running in 8f58ab2355c5
> make: Entering directory '/usr/src/app/kernel_source/5.10.31-v8/build'
>   CC [M]  /usr/src/app/example_module_headers_src/hello.o
>   MODPOST /usr/src/app/example_module_headers_src/Module.symvers
> WARNING: modpost: missing MODULE_LICENSE() in /usr/src/app/example_module_headers_src/hello.o
> ERROR: modpost: "_mcount" [/usr/src/app/example_module_headers_src/hello.ko] undefined!
> scripts/Makefile.modpost:111: recipe for target '/usr/src/app/example_module_headers_src/Module.symvers' failed
> Makefile:1728: recipe for target 'modules' failed
> make: Leaving directory '/usr/src/app/kernel_source/5.10.31-v8/build'
> make[1]: *** [/usr/src/app/example_module_headers_src/Module.symvers] Error 1
> make[1]: *** Deleting file '/usr/src/app/example_module_headers_src/Module.symvers'
> make: *** [modules] Error 2
> ```
> 
> Current workaround for me:
> Change
> cat ./layers/meta-balena/meta-balena-common/recipes-kernel/linux/files/Dockerfile
> 
> ```
> # Compile external hello module using header sources
> RUN ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_source/*/build modules_prepare
> RUN ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_source/*/build/ M=/usr/src/app/example_module_headers_src
> 
> # Compile external hello module using pre-built headers
> # We run modules_prepare again because the tools pre-compiled are actually the target device arch. While we cross-compile for testing.
> RUN ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_modules_headers/ modules_prepare
> RUN ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_modules_headers/ M=/usr/src/app/example_module_headers_built
> ```
> 
> To
> 
> ```
> # Compile external hello module using header sources
> RUN ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_source/*/build modules_prepare
> #RUN ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_source/*/build/ M=/usr/src/app/example_module_headers_src
> 
> # Compile external hello module using pre-built headers
> # We run modules_prepare again because the tools pre-compiled are actually the target device arch. While we cross-compile for testing.
> RUN ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_modules_headers/ modules_prepare
> #RUN ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_modules_headers/ M=/usr/src/app/example_module_headers_built
> ```

Hi @Razikus this PR should now be good to merge and I will merge it soon. Fixed all the issues with it. Thanks for the interest.

**Comment by Razikus** [comment]
Great man, it's great timing because i just need this :D

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
@floion add a fixes #601 and #676 to the commit please.

**Comment by floion** [comment]
Fixes #601 
Fixes #676

**Comment by floion** [comment]
@balena-ci I self-certify!

**Pull request merged**
