### PR TITLE
layers/meta-balena: Update to v2.87.18

### PR DESCRIPTION
**Pull request by acostach**
Update meta-balena from 2.87.16 to 2.87.18

Changelog-entry: Update meta-balena from v2.87.16 to v2.87.18
Signed-off-by: Alexandru Costache <alexandru@balena.io>

### CODE REVIEW

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@balena-ci I self-certify!

**Comment by floion** [comment]
@balena-ci rebase

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
Superseded by the 2.88.4 update PR

**Pull request closed without merging**
