### PR TITLE
balena-yocto-scripts: Update balena-yocto-scripts to v1.10.3

### PR DESCRIPTION
**Pull request by klutchell**
Change-type: patch
Changelog-entry: Update balena-yocto-scripts to v1.10.3
Signed-off-by: Kyle Harding <kyle@balena.io>

### CODE REVIEW

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by vipulgupta2048** [comment]
@resin-jenkins retest this please

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Comment by klutchell** [comment]
@balena-ci I self-certify!

**Pull request merged**
