### PR TITLE
balena-yocto-scripts: update to v1.9.1

### PR DESCRIPTION
**Pull request by klutchell**
v1.9.1 includes a new step to package ./tests with the jenkins artifacts.

Changelog-entry: Update balena-yocto-scripts to v1.9.1
Connects-to: balena-os/balena-yocto-scripts#181
Signed-off-by: Kyle Harding <kyle@balena.io>

### CODE REVIEW

**Comment by klutchell** [comment]
@resin-jenkins rebase

**Review by alexgg — COMMENTED** [review]
@klutchell for device repositories we always need a `Changelog-entry`. That always catches me.

**Comment by alexgg** [comment]
@klutchell and it does not need a `Change-type`

**Comment by klutchell** [comment]
@resin-jenkins add to whitelist

**Comment by klutchell** [comment]
@resin-jenkins ok to test

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Review by alexgg — APPROVED** [review]
lgtm

**Pull request merged**
