### PR TITLE
linux-raspberrypi: Include aufs module for devices that have been usi…

### PR DESCRIPTION
**Pull request by acostach**
…ng aufs

Changelog-entry: linux-raspberrypi: Include aufs module for devices that have been using aufs
Signed-off-by: Alexandru Costache <alexandru@balena.io>

### CODE REVIEW

**Comment by rcooke-warwick** [comment]
@resin-jenkins retest this please

**Comment by rcooke-warwick** [comment]
@balena-ci retest

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Review by klutchell — APPROVED** [review]

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Pull request merged**
