### PR TITLE
linux: Remove unused patch

### PR DESCRIPTION
**Pull request by imrehg**
It's not used since 631b4d56c126e04f59183674404d84a6016bdf29.

Changelog-entry: Remove unused patch of the kernel
Signed-off-by: Gergely Imreh <gergely@balena.io>

### CODE REVIEW

**Comment by imrehg** [comment]
@agherzan can you tell Jenkins to build this? Thanks!

**Comment by agherzan** [comment]
@resin-jenkins add to whitelist

**Comment by agherzan** [comment]
@resin-jenkins ok to test

**Comment by imrehg** [comment]
@resin-jenkins retest this please

**Comment by imrehg** [comment]
@agherzan @floion seems like Jenkins don't wanna build this so far, any thoughts? (not urgent, just confusing)

**Comment by floion** [comment]
@resin-jenkins add to whitelist

**Pull request merged**
