### PR TITLE
Add rpi5 from temp repo

### PR DESCRIPTION
**Pull request by floion**

### CODE REVIEW

**Comment by floion** [comment]
@balena-ci I self-certify!

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
@floion the current RPI5 is [using](https://github.com/balena-os/meta-raspberrypi-temp/commit/6f1f2f005c2416538009423d69967b990d9d2bb3) a 6.6 kernel - maybe we should add this recipe to meta-balena-raspberrypi too. We don't want to deploy a newer version that downgrades the kernel.

**Review by alexgg — CHANGES_REQUESTED** [review]
Please review the kernel version

**Comment by floion** [comment]
@alexgg this PR just moves it over to the public repo, but my plan was to still keep deploying from the temp repo for the time being until we have the BSP updated here and that would bring the kernel version on par or newer

**Comment by alexgg** [comment]
> @alexgg this PR just moves it over to the public repo, but my plan was to still keep deploying from the temp repo for the time being until we have the BSP updated here and that would bring the kernel version on par or newer

makes sense @floion thanks.

**Comment by floion** [comment]
@alexgg so can we merge this PR?

**Review by alexgg — APPROVED** [review]

**Pull request merged**
