### PR TITLE
Add Pi0 2 W support, switch to honister syntax compat

### PR DESCRIPTION
**Pull request by acostach**
Known issues in this PR:
1) <strike> console is not applied to cmdline in development images</strike> - addressed
2) <strike>BALENA_STORAGE is set to overlay2 for all boards</strike>- not an issue

### CODE REVIEW

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@balena-ci retest

**Comment by acostach** [comment]
Let's not merge this PR since it's making use of unmerged PRs - https://github.com/balena-os/balena-raspberrypi/pull/725/commits/fb867f40c4ad09389afc3d132c4a9fdf35bc356c / https://github.com/balena-os/balena-raspberrypi/pull/725/commits/1785de4dbdba9827ccc6fd19f59f3b0b2626e515

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
Adding Pi0 2W in https://github.com/balena-os/balena-raspberrypi/pull/733 

There is not enough rootfs space on Pi4 with honister. Too many files libraries and binaries in the rootfs have small increases in size which add up, and the Pi4 is already very tight on space: balena-image-1.0-r0 do_image_size_check: The disk aligned root filesystem size 282624 exceeds the available space 274432. In Dunfell the rootfs dir in the build directory is 271M and with Honister it is 283M. Firmware directory size is the same.

**Comment by acostach** [comment]
Superseded by https://github.com/balena-os/balena-raspberrypi/pull/755

**Pull request closed without merging**
