### PR TITLE
balena-yocto-scripts: Update balena-yocto-scripts to v1.17.5

### PR DESCRIPTION
**Pull request by klutchell**
Update balena-yocto-scripts from 1.17.2 to 1.17.5

Changelog-entry: Update balena-yocto-scripts from v1.17.2 to v1.17.5
Change-type: patch

### CODE REVIEW

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
Superseded by https://github.com/balena-os/balena-raspberrypi/pull/815

**Pull request closed without merging**
