### PR TITLE
Update rust to 1.33

### PR DESCRIPTION
**Pull request by agherzan**

### CODE REVIEW

**Comment by agherzan** [comment]
@resin-jenkins add to whitelist

**Comment by agherzan** [comment]
@resin-jenkins ok to test

**Comment by floion** [comment]
Is 1.33 a tag? Maybe provide the revision in the git log if 1.33 is not a particular tag?

**Comment by agherzan** [comment]
@floion the revision is in the commit itself as it changes the submodule.

**Comment by floion** [comment]
Sure the revision is in the commit itself. I was asking for brevity in this case.

**Comment by floion** [comment]
Why do we need rust 1.33 for?

**Comment by agherzan** [comment]
@floion it is a dependency of the new os-config. Also, we wanted to unify the rust compiler version across our devices.

**Pull request merged**
