### PR TITLE
balena-yocto-scripts: Update to v1.16.3

### PR DESCRIPTION
**Pull request by alexgg**
Update balena-yocto-scripts from v1.16.0 to v1.16.2

Change-type: patch
Changelog-entry: Update balena-yocto-scripts to v1.16.2
Signed-off-by: Alex Gonzalez <alexg@balena.io>

### CODE REVIEW

**Comment by alexgg** [comment]
@balena-ci retest

**Comment by acostach** [comment]
Hi @vipulgupta2048 looks like this failed again today for the Pi3 https://jenkins.product-os.io/job/leviathan-raspberrypi3/1027/ and a rollback altboot file is again found, just like in my PR #755 . The artifacts on 755 have shown no failure while running the hup suite in a loop on my local testbot, I'll try with the artifact from the current PR again right now but I suspect there could be an usecase that's happening solely on the testbot. I'll get back with my local testbot result

**Comment by acostach** [comment]
https://github.com/balena-os/balena-raspberrypi/pull/765 will need to be included first as per https://www.flowdock.com/app/rulemotion/r-resinos/threads/VFsuTAJbu0tUS8ihXhQJaSLoKDm , because on the first hup after the switch the storage is still aufs, and should be migrated on the next hup. The last meta-balena update PR included the switch to overlay2 and should have failed the leviathan tests.

**Comment by alexgg** [comment]
@balena-ci I self-certify!

**Pull request merged**
