### PR TITLE
fix: github issue link

### PR DESCRIPTION
**Pull request by kennethlimcp**
missing `-` in the github repo link for opening issues.

### CODE REVIEW

**Comment by kennethlimcp** [comment]
@floion able to review?

**Comment by floion** [comment]
Hi @kennethlimcp thanks for the contribution. Please follow the guidelines from https://github.com/balena-os/balena-raspberrypi#contributing

**Comment by kennethlimcp** [comment]
@floion did the rebase..

Not sure if this works?

```
fix: github issue link

This commit fixes the link that allows a user to report an issue at the aggregate repository.

Signed-off-by: Kenneth Lim <kennethlimcp@gmail.com>
```

**Comment by floion** [comment]
Hi @kennethlimcp can you also rebase your branch against master and then push again? Should be enough if you `git checkout master && git pull` and then `git checkout <your branch>` and then `git rebase master`

And then, the commit log should be `Component: short description` so that would mean `README.md: Fix github issue link` and then you also need to add a `Changelog-entry` in which you add a similar description that would make it into the changelog: https://github.com/balena-os/balena-raspberrypi/blob/master/CHANGELOG.md

See one example: https://github.com/balena-os/balena-raspberrypi/pull/496/commits/665d3b7fcf39cf0ae4ca61ca75682eba03cf08fc

**Comment by kennethlimcp** [comment]
Hope this works :D

```
fix: github issue link

This commit fixes the broken link that allows a user to report an issue at the aggregate repository.

Changelog-entry: Update README.md with the correct link for reporting an issue at the aggregate repository.

Signed-off-by: Kenneth Lim <kennethlimcp@gmail.com>
```

**Comment by floion** [comment]
Getting closer :)
Can you remove the newline between Changelog-entry and Signed-off-by? That will most likely trip off version bot we use.
Also, can you change the header to say instead `README.md: Fix github issue link` ? That would make it more inline with the contribution guide which mentions `<component>: Short description` so it's more descriptive.
Thanks and sorry for the hassle :)

**Comment by kennethlimcp** [comment]
```
README.md: Fix github issue link

This commit fixes the broken link that allows a user to report an issue at the aggregate repository.

Changelog-entry: Update README.md with the correct link for reporting an issue at the aggregate repository.
Signed-off-by: Kenneth Lim <kennethlimcp@gmail.com>
```

**Comment by floion** [comment]
@resin-jenkins ok to test

**Comment by floion** [comment]
@balena-ci retest

**Pull request closed without merging**
