### PR TITLE
layers/meta-balena: Update to v2.91.1

### PR DESCRIPTION
**Pull request by floion**
Update meta-balena from 2.89.19 to 2.91.1

Changelog-entry: Update meta-balena from v2.89.19 to v2.91.1
Signed-off-by: Florin Sarbu <florin@balena.io>

### CODE REVIEW

**Comment by floion** [comment]
@balena-ci I self-certify!

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Pull request merged**
