### PR TITLE
Restore rtl8188eufw firmware for cm4-ioboard and pi400 

### PR DESCRIPTION
**Pull request by klutchell**
Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>

Draft PR to test changes for this JF ticket: https://jel.ly.fish/support-thread-discourse-346995

### CODE REVIEW

**Comment by alexgg** [comment]
@klutchell could we maybe enable firmware compression in this boards (assuming the kernel is >= 5.3) and bring back all the firmware we left out for space reasons?

**Comment by keenanjohnson** [comment]
This is really helpful for me and my work on https://github.com/Ribbit-Network/ribbit-network-frog-sensor! let me know if I can help test or do anything to accelerate the deployment of this change!

**Comment by klutchell** [comment]
Thanks for offering @keenanjohnson!

I actually have another PR to enable firmware compression and re-add _all_ the supported firmware files, but it needs some work on my side to fix the compile errors. You can follow the progress over here: https://github.com/balena-os/balena-raspberrypi/pull/709

**Comment by keenanjohnson** [comment]
Thanks @klutchell! I'll follow that issue!

**Comment by klutchell** [comment]
Superseded by https://github.com/balena-os/balena-raspberrypi/pull/713

**Pull request closed without merging**
