### PR TITLE
layers/meta-balena: Update to v5.1.60

### PR DESCRIPTION
**Pull request by alexgg**
Update meta-balena from 5.1.58 to 5.1.60

Changelog-entry: Update meta-balena from v5.1.58 to v5.1.60

### CODE REVIEW

**Comment by rcooke-warwick** [comment]
retried all job s now the queue is not as busy

**Comment by alexgg** [comment]
lgtm

**Comment by alexgg** [comment]
Re-testing `test-raspberrypi3`

**Comment by alexgg** [comment]
Rebuilt the raspberrypi3 to re-run `test-raspberrypi3`

**Comment by alexgg** [comment]
Replaced with https://github.com/balena-os/balena-raspberrypi/pull/1157

**Pull request closed without merging**
