### PR TITLE
Update to kirkstone

### PR DESCRIPTION
**Pull request by alexgg**
Requires https://github.com/balena-os/meta-balena/pull/2803
Requires https://github.com/balena-io-hardware/balena-fin/pull/98

### CODE REVIEW

**Comment by alexgg** [comment]
@balena-ci rebase

**Review by acostach — APPROVED** [review]
lgtm

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
Waiting for meta-balena update https://github.com/balena-os/balena-raspberrypi/pull/925

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
RPI4:
```
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.416Z][52ea272-os]             not ok 2 - Device should show one record with our ntp server
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.417Z][52ea272-os]               ---
jenkins-leviathan-v2-template-8555-client-1  |               at:
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.417Z][52ea272-os]                 line: 58
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.417Z][52ea272-os]                 column: 18
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.417Z][52ea272-os]                 file: /data/suite/tests/config-json/index.js
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.417Z][52ea272-os]               found:
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.417Z][52ea272-os]                 !error
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.418Z][52ea272-os]                 name: Error
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.418Z][52ea272-os]                 message: |-
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.418Z][52ea272-os]                   Condition async () => {
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.418Z][52ea272-os]                   							return context.worker.executeCommandInHostOS(
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.419Z][52ea272-os]                   								`chronyc sources | grep -q ${ntpServer('.*')} ; echo $?`,
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.419Z][52ea272-os]                   								context.link,
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.419Z][52ea272-os]                   							).then((exitCode) => {
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.420Z][52ea272-os]                   								return Promise.resolve(exitCode === '0');
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.420Z][52ea272-os]                   							});
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.420Z][52ea272-os]                   						} timed out
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.420Z][52ea272-os]                 stack: |-
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.420Z][52ea272-os]                   Error: Condition async () => {
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.420Z][52ea272-os]                   							return context.worker.executeCommandInHostOS(
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.420Z][52ea272-os]                   								`chronyc sources | grep -q ${ntpServer('.*')} ; echo $?`,
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.421Z][52ea272-os]                   								context.link,
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.421Z][52ea272-os]                   							).then((exitCode) => {
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.421Z][52ea272-os]                   								return Promise.resolve(exitCode === '0');
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.421Z][52ea272-os]                   							});
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.421Z][52ea272-os]                   						} timed out
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.421Z][52ea272-os]                       at _waitUntil (/usr/app/lib/common/utils.js:103:11)
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.422Z][52ea272-os]                       at _waitUntil (/usr/app/lib/common/utils.js:118:11)
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.422Z][52ea272-os]                       at Object.waitUntil (/usr/app/lib/common/utils.js:121:3)
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.422Z][52ea272-os]               source: |
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.422Z][52ea272-os]                 				.then(() => {
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.422Z][52ea272-os]                 					return test.resolves(
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.422Z][52ea272-os]                 -----------------^
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.422Z][52ea272-os]                 						this.utils.waitUntil(async () => {
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.422Z][52ea272-os]                 							return context.worker.executeCommandInHostOS(
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.423Z][52ea272-os]               ...
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.437Z][52ea272-os] 
jenkins-leviathan-v2-template-8555-client-1  | [2022-11-27T20:11:05.438Z][52ea272-os]          
```

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
-raspberrypi4-unipi-neuron
```
jenkins-leviathan-v2-template-10532-client-1  | [2022-12-20T12:43:54.522Z][4c07b5a-cloud]         # Subtest: Move device to multicontainer App
jenkins-leviathan-v2-template-10532-client-1  | [2022-12-20T12:43:54.522Z][4c07b5a-cloud]             # Waiting for device: 664066fd26284108a9459f9d8c744453 to run services: frontend,proxy,data at commit: 8dba67a572caf2c3fbe5db12c0515d1c

...
jenkins-leviathan-v2-template-10532-client-1  | [2022-12-20T12:49:12.765Z][4c07b5a-cloud]             # Waiting for device: 664066fd26284108a9459f9d8c744453 to run services: frontend,proxy,data at commit: 8dba67a572caf2c3fbe5db12c0515d1c
jenkins-leviathan-v2-template-10532-client-1  | [2022-12-20T12:49:18.229Z][4c07b5a-cloud]             # Waiting for device: 664066fd26284108a9459f9d8c744453 to run services: frontend,proxy,data at commit: 8dba67a572caf2c3fbe5db12c0515d1c
jenkins-leviathan-v2-template-10532-client-1  | [2022-12-20T12:49:23.789Z][4c07b5a-cloud]             # Waiting for device: 664066fd26284108a9459f9d8c744453 to run services: frontend,proxy,data at commit: 8dba67a572caf2c3fbe5db12c0515d1c
jenkins-leviathan-v2-template-10532-client-1  | [2022-12-20T12:49:29.367Z][4c07b5a-cloud]             not ok 1 - Condition async () => {     test.comment(`Waiting for device: ${uuid} to run services: ${services} at commit: ${commit}`);     let deviceServices = await that.cloud.balena.models.device.getWithServiceDetails(       uuid       );     let running = false     running = services.every((service) => {       return (deviceServices.current_services[service][0].status === "Running") && (deviceServices.current_services[service][0].commit === commit)     })     return running;   } timed out`
```

**Comment by alexgg** [comment]
* raspberrypi4-64
  * OS FAIL
  * Cloud OK
  * HUP OK

```
# time=29391.397ms
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T11:52:34.150Z][59415ad-os] 
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.726Z][59415ad-os]             not ok 2 - Device should show one record with our ntp server
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.726Z][59415ad-os]               ---
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.726Z][59415ad-os]               at:
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.727Z][59415ad-os]                 line: 58
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.727Z][59415ad-os]                 column: 18
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.728Z][59415ad-os]                 file: /data/suite/tests/config-json/index.js
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.728Z][59415ad-os]               found:
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.728Z][59415ad-os]                 !error
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.728Z][59415ad-os]                 name: Error
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.728Z][59415ad-os]                 message: |-
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.728Z][59415ad-os]                   Condition async () => {
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.728Z][59415ad-os]                   							return context.worker.executeCommandInHostOS(
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.728Z][59415ad-os]                   								`chronyc sources | grep -q ${ntpServer('.*')} ; echo $?`,
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.728Z][59415ad-os]                   								context.link,
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.728Z][59415ad-os]                   							).then((exitCode) => {
jenkins-leviathan-v2-template-10528-client-1  |                   								return Promise.resolve(exitCode === '0');
jenkins-leviathan-v2-template-10528-client-1  |                   							});
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.728Z][59415ad-os]                   						} timed out
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.729Z][59415ad-os]                 stack: |-
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.729Z][59415ad-os]                   Error: Condition async () => {
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.729Z][59415ad-os]                   							return context.worker.executeCommandInHostOS(
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.729Z][59415ad-os]                   								`chronyc sources | grep -q ${ntpServer('.*')} ; echo $?`,
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.729Z][59415ad-os]                   								context.link,
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.729Z][59415ad-os]                   							).then((exitCode) => {
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.729Z][59415ad-os]                   								return Promise.resolve(exitCode === '0');
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.729Z][59415ad-os]                   							});
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.729Z][59415ad-os]                   						} timed out
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.730Z][59415ad-os]                       at _waitUntil (/usr/app/lib/common/utils.js:103:11)
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.730Z][59415ad-os]                       at _waitUntil (/usr/app/lib/common/utils.js:118:11)
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.730Z][59415ad-os]                       at Object.waitUntil (/usr/app/lib/common/utils.js:121:3)
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.730Z][59415ad-os]               source: |
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.730Z][59415ad-os]                 				.then(() => {
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.730Z][59415ad-os]                 					return test.resolves(
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.730Z][59415ad-os]                 -----------------^
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.731Z][59415ad-os]                 						this.utils.waitUntil(async () => {
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.731Z][59415ad-os]                 							return context.worker.executeCommandInHostOS(
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.731Z][59415ad-os]               ...
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.747Z][59415ad-os] 
jenkins-leviathan-v2-template-10528-client-1  | [2022-12-20T12:04:56.748Z][59415ad-os]             Bail out! Device sho
```

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Pull request merged**
