### PR TITLE
Add overlay for Seeed Can-bus board

### PR DESCRIPTION
**Pull request by Awk34**
Board: https://www.seeedstudio.com/2-Channel-CAN-BUS-FD-Shield-for-Raspberry-Pi-p-4072.html
Overlay: https://github.com/Seeed-Studio/seeed-linux-dtoverlays/blob/master/overlays/rpi/2xMCP2517FD-overlay.dts

### CODE REVIEW

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
Hi @Awk34 and thank you for your PR! With which rpi model do you plan to use this hat? Asking so we know which image release to schedule

**Comment by acostach** [comment]
Also @Awk34 , this PR was probably based on a slightly different kernel version, I've done a couple small changes to your patches so that they build with the current base and included them in this PR: https://github.com/balena-os/balena-raspberrypi/pull/636

**Comment by Awk34** [comment]
@acostach I will use this board with a RPI 4

**Comment by Awk34** [comment]
Superceded by #636

**Comment by Awk34** [comment]
@acostach could you point me to the build when it's done so I can test?

**Comment by acostach** [comment]
@Awk34 sure, I will let you know when it will become available in the dashboard

**Comment by acostach** [comment]
Hi @Awk34, the dashboard image v2.75.0+rev1 for the Pi4 includes the overlay you PRed.

**Comment by Awk34** [comment]
@acostach I updated my device to the new build, added `dtoverlay="2xmcp2517fd"`, and ran `dmesg | grep spi` and the board shows up:

```
spi_master spi0: will run message pump with realtime priority
mcp251xfd spi0.0 (unnamed net_device) (uninitialized): Detected MCP2518FD, but firmware specifies a MCP2517FD. Fixing up.
mcp251xfd spi0.0 can0: MCP2518FD rev0.0 (-RX_INT -MAB_NO_WARN +CRC_REG +CRC_RX +CRC_TX +ECC -HD c:40.00MHz m:20.00MHz r:17.00MHz e:0.00MHz) successfully initialized.
spi_master spi1: will run message pump with realtime priority
mcp251xfd spi1.0 (unnamed net_device) (uninitialized): Detected MCP2518FD, but firmware specifies a MCP2517FD. Fixing up.
mcp251xfd spi1.0 can1: MCP2518FD rev0.0 (-RX_INT -MAB_NO_WARN +CRC_REG +CRC_RX +CRC_TX +ECC -HD c:40.00MHz m:20.00MHz r:17.00MHz e:0.00MHz) successfully initialized
```

The CAN channels show up when running `ifconfig -a` as well:

```
can0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          NOARP  MTU:16  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:10 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:43 

can1      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          NOARP  MTU:16  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:10 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:44
```

**Pull request closed without merging**
