### PR TITLE
linux-raspberrypi: update to latest stable head 5.15.92

### PR DESCRIPTION
**Pull request by alexgg**
Change-type: patch

### CODE REVIEW

**Comment by alexgg** [comment]
Check that the built image is configured with `TOUCHSCREEN_EDT_FT5X06=m`

**Comment by floion** [comment]
Is this for a request for that touchscreen support?

**Comment by alexgg** [comment]
> Is this for a request for that touchscreen support?

It is @floion

**Comment by alexgg** [comment]
For `raspberrypi0-2w`:
```
# CONFIG_TOUCHSCREEN_MK712 is not set
# CONFIG_TOUCHSCREEN_PENMOUNT is not set
CONFIG_TOUCHSCREEN_EDT_FT5X06=m
```

**Comment by alexgg** [comment]
lgtm

**Comment by mtoman** [comment]
@resin-jenkins retest this please

**Comment by mtoman** [comment]
@resin-jenkins retest this please

**Comment by mtoman** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
NFS cache is full, waiting on resolution to re-trigger builds.

**Comment by Kappers** [comment]
Please can someone help unblock this PR? It should incorporate important fixes for several known issues (https://github.com/raspberrypi/linux/issues/3919, https://github.com/raspberrypi/linux/issues/5088, https://github.com/raspberrypi/linux/issues/5495) - one of which is mine! It would be useful to test the updated OS urgently. Thank you!

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Pull request merged**
