### PR TITLE
Kernel 5.10

### PR DESCRIPTION
**Pull request by jakogut**
This kernel requires fewer patches with better upstream support, and has better supports KMS. More information here: https://www.raspberrypi.org/forums/viewtopic.php?t=288234

Additionally, we've had users request support for this kernel: https://github.com/balena-os/balena-raspberrypi/issues/601

This is a WIP branch to add support for kernel 5.10 (derived from upstream meta-raspberrypi) to balena-raspberrypi.

### CODE REVIEW

**Comment by jakogut** [comment]
@resin-jenkins add to whitelist

**Comment by jakogut** [comment]
There are a few issues with this PR as it stands, and I wanted to get some feedback on them now that it builds.

First, the kernel doesn't boot. U-boot runs and loads the kernel, but the boot stops at `Starting kernel...`, there's no LED status light indicating that the kernel is running, and it never comes on the network. I thought it might have been a firmware incompatibility issue, so I updated to the version from `meta-raspberrypi` to no effect.

```
U-Boot 2020.07 (Jul 18 2020 - 15:34:49 +0000)

DRAM:  7.9 GiB
RPI 4 Model B (0xd03114)
MMC:   mmcnr@7e300000: 1, emmc2@7e340000: 0
Loading Environment from FAT... *** Warning - bad CRC, using default environment

In:    serial
Out:   erial
Err:   serial
Net:   eth0: ethernet@7d580000
PCIe BRCM: link up, 5.0 Gbps x1 (SSC)
starting USB...
No working controllers founderror -110
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
516 bytes rea in 11 ms (44.9 KiB/s)
## Executing script at 02400000
Scanning mmc usb devices 0 1 2
24 bytes read in 14 ms (1000 Bytes/s)
Found esin image on mmc 0
Loading resinOS_uEnv.txt from mmc device 0 partition 1
Failed to load 'resinOS_uEnv.txt'
Loading extrauEnv.txt from mmc device 0 partition 1
0 bytes read in 12 ms (0 Bytes/s)
Import extra_uEnv.txt in environment
Loading botcount.env from mmc device 0 partition 1
Failed to load 'bootcount.env'
No bootcount.env file. Setting bootcount=0 in evironment
12759288 bytes read in 569 ms (21.4 MiB/s)
Uncompressed size: 32451072 = 0x1EF2A00
Moving Image from 0x80000 to 0x20000, end=2230000
## Flattened Device Tree blob at 2eff3b00
   Booting using the fdt blob at 0x2eff3b00
   Using Device Tree n place at 000000002eff3b00, end 000000002f002fa8

Starting kernel ...
```

Additionally, the build fails on kernel-module-headers with: `gen_mod_headers: Missing kernel configuration.` Specifying `BALENA_DISABLE_KERNEL_HEADERS=1` works around this, but I'd like to understand what's missing here.

**Comment by jakogut** [comment]
We'll probably also want to drop the commit making kernel 5.10 the default before merging this, and then I'm not sure how or at what point we want to distribute this kernel.

**Comment by krasi-georgiev** [comment]
@jakogut thanks for working on this. I am the one that requested this :)
 Are there any blockers to progress with the PR or just waiting for some feedback from the maintainers?

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
@jakogut You're seeing some weird behaviour because you-re missing `inherit kernel-resin` in your kernel recipe.

**Comment by klutchell** [comment]
I pushed some suggested changes in a new commit. Feel free to use it, or drop it, I won't be offended either way :D

Changes:
- copied `linux-raspberrypi.inc` and `linux-raspberrypi_5.10.bb` from meta-raspberrypi master without modifications
- created `linux-raspberrypi_5.10.bbappend` similar 5.4 but with your updated patch list
- copied `vc4graphics.cfg` and `initramfs-image-bundle.cfg` files from meta-raspberrypi master

I just noticed last compile failed (`cp: cannot stat 'arch/arm/kernel/module.lds': No such file or directory`) so there's still some work to do and it's obviously untested. Just throwing this out there in case it helps unblock you!

**Comment by jakogut** [comment]
Thanks for the assist, @klutchell! This certainly helps.

**Comment by jakogut** [comment]
@balena-ci rebase

**Comment by jakogut** [comment]
@balena-ci rebase

**Comment by smithandrewc** [comment]
I tried this on a CM4 (MACHINE=raspberrypicm4-ioboard) and it's not booting, just stops after u-boot

```
U-Boot 2021.04-rc3 (Mar 03 2021 - 15:10:34 +0000)

DRAM:  2 GiB
RPI Compute Module 4 (0xb03140)
MMC:   mmcnr@7e300000: 1, emmc2@7e340000: 0
Loading Environment from FAT... *** Warning - bad CRC, using default environment

In:    serial
Err:   serial
Net:   Could not get PHY for mdio@e14: addr 1
No ethernet found.

PCIe BRCM: link down
starting USB...
No working controllers foun
switch to partitions #0, OK
mmc0(part 0) is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
516 bytes read in 10 ms (49.8 KiB/s)
## Excuting script at 02400000
Scanning mmc usb devices 0 1 2
24 bytes read in 8 ms (2.9 KiB/s)
Found resin image on mmc 0
Loading resinOS_uEnvtxt from mmc device 0 partition 1
Failed to load 'resinOS_uEnv.txt'
Loading extra_uEnv.txt from mmc device 0 partition 1
0 bytes read i 11 ms (0 Bytes/s)
Import extra_uEnv.txt in environment
Loading bootcount.env from mmc device 0 partition 1
Failed to load 'bootount.env'
No bootcount.env file. Setting bootcount=0 in environment
14001486 bytes read in 625 ms (21.4 MiB/s)
Uncompressed size: 3528108 = 0x21A5A00
Moving Image from 0x80000 to 0x200000, end=24f0000
## Flattened Device Tree blob at 2eff6f00
   Booting using th fdt blob at 0x2eff6f00
   Using Device Tree in place at 000000002eff6f00, end 000000002f002fb6

Starting kernel ...
```
I expect the booting issue is a firmware issue, on other images I've updated the firmware files and it fixes the boot issue.  However, what concerns me is the failure to load the ethernet

`Net:   Could not get PHY for mdio@e14: addr 1
`
Any ideas on where to start?  I've built other meta-raspberrypi images for the CM4 using the same u-boot version and don't experience the issue.  I'm having a difficult time figuring out where it's coming from.

Thanks.

**Comment by alexgg** [comment]
@jakogut could you please take a look to @smithandrewc comment above? Thanks!

**Comment by smithandrewc** [comment]
Copying in a working bcm2711-rpi-cm4.dtb fixed the ethernet/mdio problem.

Copying in working firmware files (fixup4cd.dat, fixup4.dat, fixup4x.dat, start4cd.elf, start4.elf, start4x.elf) fixes the booting problem.

**Comment by jakogut** [comment]
@smithandrewc Awesome, glad to hear you got it working! I'll look at updating this PR with those changes.

**Comment by jakogut** [comment]
@balena-ci rebase

**Comment by smithandrewc** [comment]
I recompiled this and I'm still get the same error` Net: Could not get PHY for mdio@e14: addr 1` unless I overwrite the bcm2711-rpi-cm4.dtb file.  Comparing the two, the only difference I see are all the `phandle` are missing and 

```
__symbols__ {
...
};
```

By copying over the `__symbols__` section from the working one to the one compiled here, it boots up properly.  Is the device-tree compiler step being changed in one of the balena recipes?  My "working" dtb comes from a yocto compiled image from meta-raspberrypi so upstream seems to be correct.

**Comment by smithandrewc** [comment]
I added #668, which bumps the kernel version and fixes the bootfiles.  This brings it up to meta-raspberrypi hardknott.

**Comment by jakogut** [comment]
@alexgg I'm seeing a weird build failure with `kernel-headers-test` exiting with status 2.

```
ERROR: kernel-headers-test-1.0-r0 do_compile: Execution of '/home/build/build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/temp/run.do_compile.308038' failed with exit code 2:
The command '/bin/sh -c ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix}  make -C /usr/src/app/kernel_source/*/build M=/usr/src/app/example_module_headers_src && echo "compiled hello module with header sources"' returned a non-zero code: 2
WARNING: /home/build/build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/temp/run.do_compile.308038:1 exit 2 from 'IMAGE_ID=$(DOCKER_API_VERSION=1.22 docker build --build-arg kernel_arch=arm64 --build-arg cross_compile_prefix=aarch64-linux-gnu- /home/build/build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/kernel-headers-test-1.0/work)'

ERROR: Logfile of failure stored in: /home/build/build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/temp/log.do_compile.308038
Log data follows:
| DEBUG: Executing shell function do_compile
| The command '/bin/sh -c ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix}  make -C /usr/src/app/kernel_source/*/build M=/usr/src/app/example_module_headers_src && echo "compiled hello module with header sources"' returned a non-zero code: 2
| WARNING: /home/build/build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/temp/run.do_compile.308038:1 exit 2 from 'IMAGE_ID=$(DOCKER_API_VERSION=1.22 docker build --build-arg kernel_arch=arm64 --build-arg cross_compile_prefix=aarch64-linux-gnu- /home/build/build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/kernel-headers-test-1.0/work)'
| ERROR: Execution of '/home/build/build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/temp/run.do_compile.308038' failed with exit code 2:
| The command '/bin/sh -c ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix}  make -C /usr/src/app/kernel_source/*/build M=/usr/src/app/example_module_headers_src && echo "compiled hello module with header sources"' returned a non-zero code: 2
| WARNING: /home/build/build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/temp/run.do_compile.308038:1 exit 2 from 'IMAGE_ID=$(DOCKER_API_VERSION=1.22 docker build --build-arg kernel_arch=arm64 --build-arg cross_compile_prefix=aarch64-linux-gnu- /home/build/build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/kernel-headers-test-1.0/work)'
| 
ERROR: Task (/home/build/build/../layers/meta-balena/meta-balena-common/recipes-kernel/linux/kernel-headers-test.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 4222 tasks of which 3774 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/build/build/../layers/meta-balena/meta-balena-common/recipes-kernel/linux/kernel-headers-test.bb:do_compile
Summary: There were 5 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
[000000550][LOG]Build for raspberrypi4-64 failed. Check failed log in build/tmp/log/cooker/raspberrypi4-64 .
[000000550][LOG]If build for raspberrypi4-64 succeeded, final image should have been generated here:
[000000550][LOG]   build/tmp/deploy/images/raspberrypi4-64/balena-image-raspberrypi4-64.balenaos-img
[000000550][LOG]Done.
```

I tested out this image build outside of Yocto to see if we could get a more descriptive error message:

```
┌─[✗]─[13:17:57]─[joseph@wash]
└──> balena-raspberrypi $ >> docker build --build-arg kernel_arch=arm64 --build-arg cross_compile_prefix=aarch64-linux-gnu- build/tmp/work/aarch64-poky-linux/kernel-headers-test/1.0-r0/kernel-headers-test-1.0/work/
Sending build context to Docker daemon  25.61MB
Step 1/14 : FROM balenalib/intel-nuc-debian:stretch-20190717
 ---> 6d11514990a5
Step 2/14 : RUN apt-get update && apt-get install -y curl wget build-essential libelf-dev bc flex libssl-dev bison gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu python-minimal
 ---> Using cache
 ---> 3398de266875
Step 3/14 : ADD example_module /usr/src/app/example_module_headers_src/
 ---> Using cache
 ---> 870c80bc34fe
Step 4/14 : ADD example_module /usr/src/app/example_module_headers_built/
 ---> Using cache
 ---> d2aceabf498d
Step 5/14 : ADD kernel_source.tar.gz /usr/src/app/kernel_source
 ---> 9042e734d73f
Step 6/14 : ADD kernel_modules_headers.tar.gz /usr/src/app/
 ---> c6e76266a818
Step 7/14 : WORKDIR /usr/src/app
 ---> Running in eb5b27468d71
Removing intermediate container eb5b27468d71
 ---> bdf2c11b779e
Step 8/14 : RUN if [ -f /lib64/ld-linux-x86-64.so.2 ]; then 	if [ ! -f /lib/ld-linux-x86-64.so.2 ]; then 		ln -s /lib64/ld-linux-x86-64.so.2  /lib/ld-linux-x86-64.so.2 ; 	fi;     fi;
 ---> Running in 01c677c29905
Removing intermediate container 01c677c29905
 ---> f8e5ab9bcc66
Step 9/14 : ARG kernel_arch
 ---> Running in 23f64c5d6df5
Removing intermediate container 23f64c5d6df5
 ---> 60807e8e04f3
Step 10/14 : ARG cross_compile_prefix
 ---> Running in cb59b4aac77c
Removing intermediate container cb59b4aac77c
 ---> ebb38a58d451
Step 11/14 : RUN ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} make -C /usr/src/app/kernel_source/*/build modules_prepare
 ---> Running in c51c8ffffdb3
make: Entering directory '/usr/src/app/kernel_source/5.10.31-v8/build'
  SYNC    include/config/auto.conf.cmd
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  LEX     scripts/kconfig/lexer.lex.c
  YACC    scripts/kconfig/parser.tab.[ch]
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTCC  scripts/kconfig/preprocess.o
  HOSTCC  scripts/kconfig/symbol.o
  HOSTCC  scripts/kconfig/util.o
  HOSTLD  scripts/kconfig/conf
  HOSTCC  scripts/dtc/dtc.o
  HOSTCC  scripts/dtc/flattree.o
  HOSTCC  scripts/dtc/fstree.o
  HOSTCC  scripts/dtc/data.o
  HOSTCC  scripts/dtc/livetree.o
  HOSTCC  scripts/dtc/treesource.o
  HOSTCC  scripts/dtc/srcpos.o
  HOSTCC  scripts/dtc/checks.o
  HOSTCC  scripts/dtc/util.o
  LEX     scripts/dtc/dtc-lexer.lex.c
  YACC    scripts/dtc/dtc-parser.tab.[ch]
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
  HOSTCC  scripts/dtc/dtc-parser.tab.o
  HOSTLD  scripts/dtc/dtc
  HOSTCC  scripts/genksyms/genksyms.o
  YACC    scripts/genksyms/parse.tab.[ch]
  HOSTCC  scripts/genksyms/parse.tab.o
  LEX     scripts/genksyms/lex.lex.c
  HOSTCC  scripts/genksyms/lex.lex.o
  HOSTLD  scripts/genksyms/genksyms
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/recordmcount
  HOSTCC  scripts/sorttable
  HOSTCC  scripts/asn1_compiler
  HOSTCC  scripts/extract-cert
  WRAP    arch/arm64/include/generated/uapi/asm/kvm_para.h
  WRAP    arch/arm64/include/generated/uapi/asm/errno.h
  WRAP    arch/arm64/include/generated/uapi/asm/ioctl.h
  WRAP    arch/arm64/include/generated/uapi/asm/ioctls.h
  WRAP    arch/arm64/include/generated/uapi/asm/ipcbuf.h
  WRAP    arch/arm64/include/generated/uapi/asm/msgbuf.h
  WRAP    arch/arm64/include/generated/uapi/asm/poll.h
  WRAP    arch/arm64/include/generated/uapi/asm/resource.h
  WRAP    arch/arm64/include/generated/uapi/asm/sembuf.h
  WRAP    arch/arm64/include/generated/uapi/asm/shmbuf.h
  WRAP    arch/arm64/include/generated/uapi/asm/siginfo.h
  WRAP    arch/arm64/include/generated/uapi/asm/socket.h
  WRAP    arch/arm64/include/generated/uapi/asm/sockios.h
  WRAP    arch/arm64/include/generated/uapi/asm/stat.h
  WRAP    arch/arm64/include/generated/uapi/asm/swab.h
  WRAP    arch/arm64/include/generated/uapi/asm/termbits.h
  WRAP    arch/arm64/include/generated/uapi/asm/termios.h
  WRAP    arch/arm64/include/generated/uapi/asm/types.h
  WRAP    arch/arm64/include/generated/asm/early_ioremap.h
  WRAP    arch/arm64/include/generated/asm/mcs_spinlock.h
  WRAP    arch/arm64/include/generated/asm/qrwlock.h
  WRAP    arch/arm64/include/generated/asm/qspinlock.h
  WRAP    arch/arm64/include/generated/asm/set_memory.h
  WRAP    arch/arm64/include/generated/asm/user.h
  WRAP    arch/arm64/include/generated/asm/bugs.h
  WRAP    arch/arm64/include/generated/asm/delay.h
  WRAP    arch/arm64/include/generated/asm/div64.h
  WRAP    arch/arm64/include/generated/asm/dma-mapping.h
  WRAP    arch/arm64/include/generated/asm/dma.h
  WRAP    arch/arm64/include/generated/asm/emergency-restart.h
  WRAP    arch/arm64/include/generated/asm/hw_irq.h
  WRAP    arch/arm64/include/generated/asm/irq_regs.h
  WRAP    arch/arm64/include/generated/asm/kdebug.h
  WRAP    arch/arm64/include/generated/asm/kmap_types.h
  WRAP    arch/arm64/include/generated/asm/local.h
  WRAP    arch/arm64/include/generated/asm/local64.h
  WRAP    arch/arm64/include/generated/asm/mm-arch-hooks.h
  WRAP    arch/arm64/include/generated/asm/mmiowb.h
  WRAP    arch/arm64/include/generated/asm/msi.h
  WRAP    arch/arm64/include/generated/asm/rwonce.h
  WRAP    arch/arm64/include/generated/asm/serial.h
  WRAP    arch/arm64/include/generated/asm/switch_to.h
  WRAP    arch/arm64/include/generated/asm/trace_clock.h
  WRAP    arch/arm64/include/generated/asm/unaligned.h
  WRAP    arch/arm64/include/generated/asm/vga.h
  CC      scripts/mod/empty.o
  HOSTCC  scripts/mod/mk_elfconfig
  MKELF   scripts/mod/elfconfig.h
  HOSTCC  scripts/mod/modpost.o
  CC      scripts/mod/devicetable-offsets.s
  UPD     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/mod/file2alias.o
  HOSTCC  scripts/mod/sumversion.o
  HOSTLD  scripts/mod/modpost
scripts/Makefile.build:414: warning: overriding recipe for target 'modules.order'
Makefile:1424: warning: ignoring old recipe for target 'modules.order'
  CC      arch/arm64/kernel/vdso/vgettimeofday.o
  AS      arch/arm64/kernel/vdso/note.o
  AS      arch/arm64/kernel/vdso/sigreturn.o
  LD      arch/arm64/kernel/vdso/vdso.so.dbg
  VDSOSYM include/generated/vdso-offsets.h
  LDS     scripts/module.lds
make: Leaving directory '/usr/src/app/kernel_source/5.10.31-v8/build'
Removing intermediate container c51c8ffffdb3
 ---> 402b9c2a1e1c
Step 12/14 : RUN ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} KERNEL_TREE_PATH=/usr/src/app/kernel_source/*/build/ MODULE_PATH=/usr/src/app/example_module_headers_src  make -C /usr/src/app/example_module_headers_src
 ---> Running in a0b9813a14ce
make: Entering directory '/usr/src/app/example_module_headers_src'
make -C /usr/src/app/kernel_source/*/build/ M=/usr/src/app/example_module_headers_src modules
make[1]: Entering directory '/usr/src/app/kernel_source/5.10.31-v8/build'
  CC [M]  /usr/src/app/example_module_headers_src/hello.o
  MODPOST /usr/src/app/example_module_headers_src/Module.symvers
WARNING: modpost: missing MODULE_LICENSE() in /usr/src/app/example_module_headers_src/hello.o
ERROR: modpost: "_mcount" [/usr/src/app/example_module_headers_src/hello.ko] undefined!
scripts/Makefile.modpost:111: recipe for target '/usr/src/app/example_module_headers_src/Module.symvers' failed
make[2]: *** [/usr/src/app/example_module_headers_src/Module.symvers] Error 1
make[2]: *** Deleting file '/usr/src/app/example_module_headers_src/Module.symvers'
Makefile:1728: recipe for target 'modules' failed
make[1]: Leaving directory '/usr/src/app/kernel_source/5.10.31-v8/build'
make[1]: *** [modules] Error 2
Makefile:10: recipe for target 'hello.ko' failed
make: Leaving directory '/usr/src/app/example_module_headers_src'
make: *** [hello.ko] Error 2
The command '/bin/sh -c ARCH=${kernel_arch} CROSS_COMPILE=${cross_compile_prefix} KERNEL_TREE_PATH=/usr/src/app/kernel_source/*/build/ MODULE_PATH=/usr/src/app/example_module_headers_src  make -C /usr/src/app/example_module_headers_src' returned a non-zero code: 2

```

The interesting line is:
`ERROR: modpost: "_mcount" [/usr/src/app/example_module_headers_src/hello.ko] undefined!`

This looks like a compiler incompatibility to me, so I bumped the kernel to 5.10 for balena-generic as well, and there's no such error. However, bumping the base image in `meta-balena-common/recipes-kernel/linux/files/Dockerfile` from `balenalib/intel-nuc-debian:stretch-20190717` to `balenalib/intel-nuc-debian:buster-20210225` *does* resolve the issue. However, as commented in that file, we're using an older Debian release because some devices with kernel v3.10 don't build with GCC 8 from Buster.

**Comment by smithandrewc** [comment]
Yep, I changed the image-balena.bbclass to get it to compile

```
diff --git a/meta-balena-common/classes/image-balena.bbclass b/meta-balena-common/classes/image-balena.bbclass
index 9f081830..919e6d13 100644
--- a/meta-balena-common/classes/image-balena.bbclass
+++ b/meta-balena-common/classes/image-balena.bbclass
@@ -6,7 +6,8 @@ inherit image_types_balena
 
 # When building a Balena OS image, we also generate the kernel modules headers
 # and ship them in the deploy directory for out-of-tree kernel modules build
-DEPENDS += "coreutils-native jq-native ${@bb.utils.contains('BALENA_DISABLE_KERNEL_HEADERS', '1', '', 'kernel-modules-headers kernel-devsrc kernel-headers-test', d)}"
+#DEPENDS += "coreutils-native jq-native ${@bb.utils.contains('BALENA_DISABLE_KERNEL_HEADERS', '1', '', 'kernel-modules-headers kernel-devsrc kernel-headers-test', d)}"
+DEPENDS += "coreutils-native jq-native ${@bb.utils.contains('BALENA_DISABLE_KERNEL_HEADERS', '1', '', 'kernel-modules-headers kernel-devsrc', d)}"
```

Probably not an option for you, just how I got around it for my work.

**Comment by jakogut** [comment]
Thanks for the confirmation, @smithandrewc. You shouldn't need to comment out that line, instead, you should be able to disable building kernel headers with the `BALENA_DISABLE_KERNEL_HEADERS=1` config, which can be passed to barys with the `-a` flag.

 I've cherry picked the last commit from https://github.com/balena-os/balena-raspberrypi/pull/668. The first commit removing the `2xmcp2517fd.dtbo` overlay was fixed by applying a patch that was being ignored. I'll also apply the change adding the PCIe overlay.

**Comment by alexgg** [comment]
@jakogut see https://www.linuxjournal.com/content/simplifying-function-tracing-modern-gcc. As Debian Stretch is using gcc 4.6 I reckon we could change `-pg` for `-mfentry` when building the module.

**Comment by floion** [comment]
Superseded by https://github.com/balena-os/balena-raspberrypi/pull/684

**Pull request closed without merging**
