### PR TITLE
OS variants merge

### PR DESCRIPTION
**Pull request by alexgg**
Pending on the merge of https://github.com/balena-os/meta-balena/pull/2227

### CODE REVIEW

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by mtoman** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
### Console test

[x] Verify developmentMode: false or not present in config.json
  [x] Verify no serial console is available
  [x] Verify no tty console is available after `systemctl start plymouth-quit.service`
Edit developmentMode: true in config.json
[x] Verify serial console is available
[ ] Verify tty console is available after `systemctl start plymouth-quit.service`
[ ] Verify passwordless root login in serial and tty consoles

**Comment by alexgg** [comment]
### SSH login
Verify developmentMode: false or not present in config.json
- [x] Verify local SSH login not possible
- [x] Verify balena ssh login is possible
Edit developmentMode: true in config.json
- [x] Verify no os.sshKeys are present in config.json
- [x] Verify passwordless local root SSH login is possible
Add invalid os.sshKeys in config.json
- [x] Verify passwordless local SSH root login is not possible
Add valid os.sshKeys in config.json
- [x] Verify key-based local root SSH login is possible

**Comment by alexgg** [comment]
### Balena engine socket

Verify developmentMode: false or not present in config.json
- [x] Verify balena engine socket not exposed
```
DOCKER_HOST=192.168.1.88:2375 docker info
```
Edit developmentMode: true in config.json
- [x] Verify balena engine socket is exposed
```
DOCKER_HOST=192.168.1.88:2375 docker info
```

**Comment by alexgg** [comment]
@balena-ci I self-certify!

**Pull request merged**
