### PR TITLE
linux-raspberrypi, sd8887-mrvl.bb, networkmanager: balenaFin v1.1.0 compatibility

### LINKED ISSUE #288: balenaFin v1.1.0 compatibility
Add device tree changes, kernel patches and driver updates for the upcoming belenaFin v1.0.0 release

### PR DESCRIPTION
**Pull request by majorz**
1. Updates the balenaFin DT overlay with the following changes:

  * marks as non-removable the WiFi/BT module - otherwise it is continuously probed
  * sd8887 WiFi driver configuration is now part of the DT
  * LED driver config for balenaFin v1.1.0
  * i2c gpio driver uses open-drain configuration - fixes the attached RTC and LED

2. Disabling power saving mode is moved away from NetworkManager to the WiFi driver config

3. sd8887 WiFi driver and firmware updated to version 189

4. pca963x LED driver properly initializes its MODE2 register (fixes the red light)

5. Brings back the ndo_do_ioctl fallback, so that iwpriv commands are functioning - reverts
https://github.com/raspberrypi/linux/commit/8bfb3676606454ffec836f56c5dc3e69dfc0956a

6. Changes a couple of sd8887 WiFi driver error log messages to msg level (those are harmless, but users get confused)

Fixes #288

Changelog-entry: balenaFin v1.1.0 compatibility
Signed-off-by: Zahari Petkov <zahari@balena.io>

### CODE REVIEW

**Comment by majorz** [comment]
This can be reviewed now. We tested the built image.

**Comment by floion** [comment]
@resin-ci retest

**Comment by floion** [comment]
@resin-jenkins add to whitelist

**Comment by floion** [comment]
@majorz can you put each file change in it's commit?
Also, for each patch, we need `Signed-off-by` and `Upstream-status` such as here: https://github.com/balena-os/balena-raspberrypi/blob/master/layers/meta-resin-raspberrypi/recipes-kernel/linux/linux-raspberrypi/0003-media-uvcvideo-Fix-driver-reference-counting.patch#L20-L21

where the upstream status can be like described here: https://lists.yoctoproject.org/pipermail/yocto/2011-April/001237.html

**Comment by floion** [comment]
Also, as you split this PR in multiple patches, also add `Changelog-entry` to each commit or group of commits if there are multiple commits that change a part of the functionality

**Comment by majorz** [comment]
Right, I should have split those in multiple PRs indeed. On to it.

**Comment by majorz** [comment]
Closing this PR in favor of #294.

**Pull request closed without merging**
