### PR TITLE
linux-kunbus: Update to version 5.10.152

### PR DESCRIPTION
**Pull request by floion**
Changelog-entry: Update linux-kunbus to 5.10.152
Signed-off-by: Florin Sarbu <florin@balena.io>

### CODE REVIEW

**Comment by wickywaka** [comment]
Is it the same as:
https://github.com/balena-os/balena-raspberrypi/pull/917

**Comment by floion** [comment]
@balena-ci I self-certify!

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by obaidch23** [comment]
Hi @floion @resin-jenkins !
Any updates please?

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by obaidch23** [comment]
Thank you! @floion

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
Because to the particular failure case for the OS update because of the new kernel, we decided to add the new kernel as a new recipe and you can then specify the new kernel just for the revpi connect s. Will recreate this PR with the mentioned changes

**Comment by floion** [comment]
Because to the particular failure case for the OS update because of the new kernel, we decided to add the new kernel as a new recipe and you can then specify the new kernel just for the revpi connect s. Will recreate this PR with the mentioned changes

**Comment by floion** [comment]
@resin-jenkins test this please

**Pull request merged**
