### PR TITLE
layers/meta-balena: Update to v2.88.4

### PR DESCRIPTION
**Pull request by acostach**
Update meta-balena from 2.87.16 to 2.88.4

Changelog-entry: Update meta-balena from v2.87.16 to v2.88.4
Signed-off-by: Alexandru Costache <alexandru@balena.io>

### CODE REVIEW

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by vipulgupta2048** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@balena-ci I self-certify!

**Comment by klutchell** [comment]
:tada:

**Pull request merged**
