### PR TITLE
Update meta-balena with a rebase

### PR DESCRIPTION
**Pull request by alexgg**

### CODE REVIEW

**Comment by alexgg** [comment]
@balena-ci I self-certify!

**Comment by majorz** [comment]
@resin-jenkins retest this please

**Comment by majorz** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
test summary: all tests have passed in different runs, but still not all in the same run.

**Pull request merged**
