### PR TITLE
linux-raspberrypi_5.10.bbappend: Remove obsolete VL805 patch

### PR DESCRIPTION
**Pull request by floion**
The changes from this patch are now upstreamed in other form
so let's remove this obsolete backport from our layer.

With this patch being applied, the USB 2.0 ports on a Raspberry Pi 4
v1.4 (the 8GB RAM version for example) - which lacks SPI flash for the
VIA VL805 chip - do not function.

Changelog-entry: Fix USB 2.0 on Raspberry Pi 4 v1.4 by removing obsolete xhci pci patch for VL805
Signed-off-by: Florin Sarbu <florin@balena.io>

### CODE REVIEW

**Comment by floion** [comment]
@balena-ci I self-certify!

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by bbugh** [comment]
Sorry to ping, is there a scheduled release upcoming that this will be a part of? #710 is affecting our new fleet deployment, and we're back to using `balenaOS 2.75.0+rev1` in the meantime.

**Comment by klutchell** [comment]
Hey @bbugh, this was fixed in BalenaOS `2.85.2+rev3` for Raspberry Pi 4.

**Comment by bbugh** [comment]
Thank you! I checked the Changelog but was looking for the name of this PR and not the obvious message about the USB change. I appreciate the quick response!

**Pull request merged**
