### PR TITLE
layer.conf: Update with all overlays 

### PR DESCRIPTION
**Pull request by bu5hm4nn**
Since we are working toward kernel 4.14 support as well, I am submitting some of the common work as pull-requests.

As indicated by the existing comment in the file:
Update list with all overlays in 'kernel-source/arch/arm/boot/dts/overlays/' not duplicating those already in 'meta-raspberrypi/conf/machine/include/rpi-base.inc'.

### CODE REVIEW

**Comment by floion** [comment]
@resin-jenkins ok to test

**Comment by bu5hm4nn** [comment]
Yeah it compiles fine here but I can't get the jenkins and test scripts to run on my end, so I can't look into that unfortunately. Is there a way to know if the ag_sumosupport branch passed jenkins before this pull request?

**Comment by agherzan** [comment]
@bu5hm4nn there are some space issues @floion is handing now on jenkins. He will retrigger the builds as soon as.

**Comment by floion** [comment]
Hi. The sumo branch has been merged.
Can you redo this PR now please?

**Comment by floion** [comment]
No new updates for this PR so closing it for the moment

**Pull request closed without merging**
