### PR TITLE
balena-yocto-scripts: Update to v1.21.3

### PR DESCRIPTION
**Pull request by alexgg**
Update balena-yocto-scripts from v1.19.34 to v1.21.3

Change-type: patch
Changelog-entry: Update balena-yocto-scripts to v1.21.3

### CODE REVIEW

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
lgtm

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
`test-raspberrypi3` failure:

```
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:10:28.198Z][5e428d6-os] Preparing to flash, attempt 4...
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:16.322Z][5e428d6-os] Flash completed
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:16.323Z][5e428d6-os] Powering on DUT
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:16.324Z][5e428d6-os] POST https://5e428d69cf3cf9301487f10dc0cf66f8.devices.832d522710354c9ab513e72bfa0eba8a.bm.balena-dev.com/dut/on
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:18.012Z][5e428d6-os] DUT powered on
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:18.012Z][5e428d6-os] Adding dut ssh key to worker...
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:36.349Z][5e428d6-os] ssh key added!
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:36.349Z][5e428d6-os] creating tunnel to dut port 48484...
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:36.355Z][5e428d6-os] # Subtest: Unmanaged BalenaOS release suite
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:39.841Z][5e428d6-os] GET https://5e428d69cf3cf9301487f10dc0cf66f8.devices.832d522710354c9ab513e72bfa0eba8a.bm.balena-dev.com/dut/ip
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:40.462Z][5e428d6-os] creating tunnel to dut port 22222...
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:43.951Z][5e428d6-os] GET https://5e428d69cf3cf9301487f10dc0cf66f8.devices.832d522710354c9ab513e72bfa0eba8a.bm.balena-dev.com/dut/ip
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:44.420Z][5e428d6-os] creating tunnel to dut port 2375...
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:47.909Z][5e428d6-os] GET https://5e428d69cf3cf9301487f10dc0cf66f8.devices.832d522710354c9ab513e72bfa0eba8a.bm.balena-dev.com/dut/ip
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:48.427Z][5e428d6-os]     ok 1 - Should detect 4c0b2c1.local on local network and establish tunnel
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:52.387Z][5e428d6-os] Connection lost before handshake
jenkins-leviathan-v2-template-42336-client-1  | [2024-03-02T16:14:56.189Z][5e428d6-os] Connection lost before handshake
```

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by rcooke-warwick** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
Depends on https://github.com/balena-os/meta-balena/pull/3383

**Comment by alexgg** [comment]
Rebased over https://github.com/balena-os/balena-raspberrypi/pull/1110

**Pull request closed without merging**
