### PR TITLE
layers/meta-balena: Update to v2.58.3

### PR DESCRIPTION
**Pull request by floion**
Update meta-balena from 2.58.0 to v2.58.3

Changelog-entry: Update meta-balena from v2.58.0 to v2.58.3
Signed-off-by: Florin Sarbu <florin@balena.io>

### CODE REVIEW

**Comment by floion** [comment]
@balena-ci I self-certify

**Comment by floion** [comment]
@balena-ci test

**Comment by floion** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by floion** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by floion** [comment]
@balena-ci I self-certify!

**Pull request merged**
