### PR TITLE
layers/meta-balena: Update to v2.107.45

### PR DESCRIPTION
**Pull request by alexgg**
Update meta-balena from 2.107.43 to 2.107.45

Changelog-entry: Update meta-balena from v2.107.43 to v2.107.45

### CODE REVIEW

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Review by floion — APPROVED** [review]

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by rcooke-warwick** [comment]
must include fixes from https://github.com/balena-os/meta-balena/pull/3056 to pass

**Comment by alexgg** [comment]
Deprecated by https://github.com/balena-os/balena-raspberrypi/pull/1006

**Pull request closed without merging**
