### PR TITLE
linux-kunbus: Add appropriate revert patch for cgroup memory disable

### PR DESCRIPTION
**Pull request by floion**
We switched back to kernel 4.9 so we need to use an appropriate patch
for that kernel version.

Changelog-entry: Rework patch revert for cgroup memory disabling in revpi kernel 4.9
Signed-off-by: Florin Sarbu <florin@balena.io>

### CODE REVIEW

**Comment by floion** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by floion** [comment]
@resin-ci retest

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-ci retest

**Comment by floion** [comment]
@resin-ci retest

**Pull request merged**
